.PHONY: setup-hooks scrub-selfcheck scrub-tree check check-common check-ci xtask-check xtask-deny build release release-musl fmt clippy test test-ts test-py tsc types frontend frontend-css wasm-components clean launchdev stopdev check-wasm-bindings check-wasi-check-liveness check-brenn-guest surface-wasm-check surface-wasm surface-wasm-test surface-sidecar-prune wasm-bindgen-preflight jco-preflight surface-transpile npm-audit node-deps e2e build-id-leaf-gate
# Delete partially-written targets on recipe failure. Without this, a failing
# WASI-import check (or any other recipe error) leaves the target file with a
# fresh mtime, causing subsequent incremental builds to skip the gate entirely.
.DELETE_ON_ERROR:

WASM_REPLAY_SRC := brenn-wasm/components/replay
WASM_REPLAY_OUT := brenn-wasm/target/components/brenn_replay.wasm
WASM_FAULT_SRC := brenn-wasm/components/replay-fault-test
WASM_FAULT_OUT := brenn-wasm/target/components/brenn_replay_fault_test.wasm
WASM_GENERIC_SRC := brenn-wasm/components/replay-generic
WASM_GENERIC_OUT := brenn-wasm/target/components/brenn_replay_generic.wasm
WASM_PROCESSOR_DEMO_SRC := brenn-wasm/components/processor-demo
WASM_PROCESSOR_DEMO_OUT := brenn-wasm/target/components/brenn_processor_demo.wasm
WASM_PROCESSOR_EXHAUST_SRC := brenn-wasm/components/processor-exhaust
WASM_PROCESSOR_EXHAUST_OUT := brenn-wasm/target/components/brenn_processor_exhaust.wasm
WASM_PROCESSOR_DUAL_SRC := brenn-wasm/components/processor-dual
WASM_PROCESSOR_DUAL_OUT := brenn-wasm/target/components/brenn_processor_dual.wasm
WASM_PROCESSOR_STORE_RT_SRC := brenn-wasm/components/processor-store-rt
WASM_PROCESSOR_STORE_RT_OUT := brenn-wasm/target/components/brenn_processor_store_rt.wasm
WASM_PROCESSOR_MEM_EXHAUST_SRC := brenn-wasm/components/processor-mem-exhaust
WASM_PROCESSOR_MEM_EXHAUST_OUT := brenn-wasm/target/components/brenn_processor_mem_exhaust.wasm
WASM_PROCESSOR_LOG_SRC := brenn-wasm/components/processor-log
WASM_PROCESSOR_LOG_OUT := brenn-wasm/target/components/brenn_processor_log.wasm
WASM_PROCESSOR_MULTIPORT_SRC := brenn-wasm/components/processor-multiport
WASM_PROCESSOR_MULTIPORT_OUT := brenn-wasm/target/components/brenn_processor_multiport.wasm
WASM_PROCESSOR_CONFIG_SRC := brenn-wasm/components/processor-config
WASM_PROCESSOR_CONFIG_OUT := brenn-wasm/target/components/brenn_processor_config.wasm
WASM_PROCESSOR_TRANSPLANT_SRC := brenn-wasm/components/processor-transplant
WASM_PROCESSOR_TRANSPLANT_OUT := brenn-wasm/target/components/brenn_processor_transplant.wasm
WASM_PROCESSOR_MQTT_TEST_SRC := brenn-wasm/components/processor-mqtt-test
WASM_PROCESSOR_MQTT_TEST_OUT := brenn-wasm/target/components/brenn_processor_mqtt_test.wasm
WASM_PROCESSOR_TOOL_TEST_SRC := brenn-wasm/components/processor-tool-test
WASM_PROCESSOR_TOOL_TEST_OUT := brenn-wasm/target/components/brenn_processor_tool_test.wasm
WASM_GIT_FORGE_PARSER_SRC := brenn-wasm/components/git-forge-parser
WASM_GIT_FORGE_PARSER_OUT := brenn-wasm/target/components/brenn_git_forge_parser.wasm
WASM_GIT_SYNC_CONSUMER_SRC := brenn-wasm/components/git-sync-consumer
WASM_GIT_SYNC_CONSUMER_OUT := brenn-wasm/target/components/brenn_git_sync_consumer.wasm

# Component source directories are split into two lists:
# - WASM_RAW_SRCS: components using committed bindings.rs generated by
#   wit-bindgen-cli 0.58. These keep raw WIT access to prove the WIT is
#   directly consumable without the SDK (the "stable generic WIT" property
#   per design §2.4). They also need precise low-level control (exhaust
#   fixtures). WASM_BINDINGS derives from this list and check-wasm-bindings
#   targets only these. Build path: wit-bindgen rust → bindings.rs →
#   cargo build --target wasm32-unknown-unknown → wasm-tools component new.
#   No cargo-component involved.
# - WASM_GUEST_SRCS: components using brenn-guest (no bindings.rs, no
#   cargo-component, built with plain cargo + wasm-tools component new).
#
# Adding a new raw-bindings fixture: add to WASM_RAW_SRCS + WASM_COMPONENT_OUTS
#   + an eval wasm_component_rule call below.
# Adding a new brenn-guest fixture: add to WASM_GUEST_SRCS + WASM_COMPONENT_OUTS
#   + an eval wasm_guest_component_rule call below.
# clean derives from WASM_RAW_SRCS + WASM_GUEST_SRCS combined.
WASM_RAW_SRCS := \
    $(WASM_REPLAY_SRC) \
    $(WASM_FAULT_SRC) \
    $(WASM_GENERIC_SRC) \
    $(WASM_PROCESSOR_EXHAUST_SRC) \
    $(WASM_PROCESSOR_MEM_EXHAUST_SRC) \
    $(WASM_PROCESSOR_MQTT_TEST_SRC) \
    $(WASM_PROCESSOR_TOOL_TEST_SRC)

WASM_GUEST_SRCS := \
    $(WASM_PROCESSOR_DEMO_SRC) \
    $(WASM_PROCESSOR_DUAL_SRC) \
    $(WASM_PROCESSOR_STORE_RT_SRC) \
    $(WASM_PROCESSOR_MULTIPORT_SRC) \
    $(WASM_PROCESSOR_LOG_SRC) \
    $(WASM_PROCESSOR_CONFIG_SRC) \
    $(WASM_PROCESSOR_TRANSPLANT_SRC) \
    $(WASM_GIT_FORGE_PARSER_SRC) \
    $(WASM_GIT_SYNC_CONSUMER_SRC)

# Combined source list for clean target.
WASM_COMPONENT_SRCS := $(WASM_RAW_SRCS) $(WASM_GUEST_SRCS)

WASM_COMPONENT_OUTS := \
    $(WASM_REPLAY_OUT) \
    $(WASM_FAULT_OUT) \
    $(WASM_GENERIC_OUT) \
    $(WASM_PROCESSOR_DEMO_OUT) \
    $(WASM_PROCESSOR_EXHAUST_OUT) \
    $(WASM_PROCESSOR_DUAL_OUT) \
    $(WASM_PROCESSOR_STORE_RT_OUT) \
    $(WASM_PROCESSOR_MEM_EXHAUST_OUT) \
    $(WASM_PROCESSOR_LOG_OUT) \
    $(WASM_PROCESSOR_MULTIPORT_OUT) \
    $(WASM_PROCESSOR_CONFIG_OUT) \
    $(WASM_PROCESSOR_TRANSPLANT_OUT) \
    $(WASM_PROCESSOR_MQTT_TEST_OUT) \
    $(WASM_PROCESSOR_TOOL_TEST_OUT) \
    $(WASM_GIT_FORGE_PARSER_OUT) \
    $(WASM_GIT_SYNC_CONSUMER_OUT)

# Committed bindings.rs files for raw-bindings components only.
# check-wasm-bindings verifies these stay in sync with the WIT.
# brenn-guest-based components have no committed bindings.rs.
WASM_BINDINGS := $(addsuffix /src/bindings.rs,$(WASM_RAW_SRCS))

# Shared CARGO_TARGET_DIR for all component crates. abspath is required because
# recipes cd into each crate dir and a relative path would resolve against the
# crate's cwd. Using an explicit override (rather than env -u) both defeats CI's
# exported CARGO_TARGET_DIR and points all 8 crates at one dep cache so shared
# deps (wit-bindgen-rt, etc.) compile once per cold build instead of once per
# fixture. Override-able (?=) so CI can export WASM_COMPONENTS_TARGET pointing
# at a persistent dir outside the checkout (matching the host-crate cache
# strategy for cross-run warmth). The cp source path is derived from this var
# so an override cannot recreate the original artifact-path mismatch.
WASM_COMPONENTS_TARGET ?= $(abspath brenn-wasm/components/target)

# Build identifier shared between the Rust binary (env! in
# brenn/src/build_info.rs) and the JS bundle (esbuild --define).
# Both ends must match for the stale-tab force-refresh handshake to
# green-light a WS connect. CI overrides this via BRENN_BUILD_ID in
# $GITHUB_ENV (set by the "Determine version" step); local dev falls
# back to the short git SHA so same-checkout builds handshake cleanly.
BRENN_BUILD_ID ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown-dev)
export BRENN_BUILD_ID

# Verbosity toggle. `make check` is quiet (one line on success; on failure the
# failing step name + its captured output). `make check V=1` streams every step
# live and drops the -q flags below. Command-line V=1 auto-propagates to the
# inner $(MAKE) <step> calls via MAKEFLAGS, so sub-targets go verbose too.
Q := $(if $(V),,-q)

# Full pre-commit check suite. Runs each step in sequence; in quiet mode each
# step's output is buffered and only printed if that step fails (large dumps are
# then persisted by the agent harness anyway). Steps stay independently
# invocable (e.g. `make clippy`) and stream normally when run directly.
xtask-check:
	cargo run -p xtask -- check

xtask-deny:
	cargo run -p xtask -- deny

# Check steps split by whether they contend for the cargo build-dir lock.
# CARGO_CHECK_STEPS share the root target/ (must run serially, in order). The
# `test` step runs the workspace suite, which includes the ts-rs export tests —
# those rewrite frontend/src/generated/*.ts as a side effect.
#
# The non-cargo steps touch no cargo lock, but they are NOT all independent of
# the cargo pipeline:
#   NONCARGO_PARALLEL_STEPS — test-py + npm-audit consume nothing the cargo lane
#     produces, so they overlap it freely. A step qualifies here only if it ALSO
#     writes nothing under the repo working tree: `xtask check` lanes walk the
#     tree concurrently, so a parallel step that writes anywhere in the repo
#     (even a cache like __pycache__/) races the walkers and trips an
#     intermittent stat panic. See the lane invariant in xtask/src/main.rs.
#   NONCARGO_AFTER_STEPS — test-ts (vitest) and tsc read the generated .ts files
#     that the `test` step rewrites. Running them concurrently with `test` races
#     that rewrite (stale-but-green type-check, or a mid-write parse error), so
#     they run only after the cargo lane finishes and the generated types settle.
CARGO_CHECK_STEPS := fmt xtask-check surface-wasm-check test
NONCARGO_PARALLEL_STEPS := test-py npm-audit build-id-leaf-gate scrub-selfcheck
NONCARGO_AFTER_STEPS := test-ts tsc
NONCARGO_CHECK_STEPS := $(NONCARGO_PARALLEL_STEPS) $(NONCARGO_AFTER_STEPS)

# Parallelism knob, shared with `xtask check` internals: BRENN_CHECK_JOBS.
# The Makefile side is BINARY (overlap on/off), not a concurrency count:
#   unset / N>1 → overlap: run all NONCARGO_CHECK_STEPS concurrently with the
#                 cargo pipeline (the numeric magnitude does not bound this side;
#                 it only bounds the lane pool inside `xtask check`).
#   0 or 1      → fully serial (original one-step-at-a-time behavior).
# A present-but-non-numeric value is a hard error (validated in check-common
# with `^[0-9]+$`). The `xtask check` parse accepts the identical digits-only
# grammar (empty = unset on both sides), so the two consumers never disagree.
# CI leaves BRENN_CHECK_JOBS unset and runs fully parallel. This is safe because
# every step that overlaps the tree-walking `xtask check` lanes is tree-read-only
# (the NONCARGO_PARALLEL_STEPS admission rule above); the cargo steps that DO write
# the tree (`test` rewriting the generated .ts) run serially in the foreground, and
# the steps reading those writes are held to NONCARGO_AFTER_STEPS so nothing reads a
# mid-write .ts. Overlap cuts wall time.

# Shared check steps: everything that runs in CI and locally (no cargo-deny).
# Quiet mode buffers each step's output to a tmp file and prints it only if that
# step fails; V=1 streams live. In parallel mode the node dependencies are
# materialized first (so a background `npm ci` can never wipe node_modules out
# from under a concurrent tsc/vitest), the cargo-independent non-cargo steps run
# in the background while the cargo steps run serially in the foreground, and the
# generated-types-consuming steps (test-ts, tsc) run once the cargo lane has
# settled the generated .ts files. Failures from every step are surfaced and the
# recipe exits nonzero if any failed.
check-common:
	@jobs="$${BRENN_CHECK_JOBS:-}"; \
	if [ -n "$$jobs" ] && ! echo "$$jobs" | grep -qE '^[0-9]+$$'; then \
	    echo "ERROR: BRENN_CHECK_JOBS must be a non-negative integer (0/1 = serial), got '$$jobs'"; exit 1; \
	fi; \
	run_step() { \
	    step="$$1"; \
	    if [ -n "$(V)" ]; then \
	        $(MAKE) $$step || { echo "FAILED: $$step"; return 1; }; \
	    else \
	        tmp=$$(mktemp); \
	        if $(MAKE) $$step >"$$tmp" 2>&1; then rm -f "$$tmp"; \
	        else echo "FAILED: $$step"; cat "$$tmp"; rm -f "$$tmp"; return 1; fi; \
	    fi; \
	}; \
	if [ "$$jobs" = "0" ] || [ "$$jobs" = "1" ]; then \
	    for step in $(CARGO_CHECK_STEPS) $(NONCARGO_CHECK_STEPS); do \
	        run_step $$step || exit 1; \
	    done; \
	else \
	    run_step node-deps || exit 1; \
	    pids=""; \
	    for step in $(NONCARGO_PARALLEL_STEPS); do \
	        run_step $$step & pids="$$pids $$!"; \
	    done; \
	    rc=0; \
	    for step in $(CARGO_CHECK_STEPS); do \
	        if ! run_step $$step; then rc=1; break; fi; \
	    done; \
	    if [ "$$rc" -eq 0 ]; then \
	        for step in $(NONCARGO_AFTER_STEPS); do \
	            run_step $$step & pids="$$pids $$!"; \
	        done; \
	    fi; \
	    for pid in $$pids; do wait $$pid || rc=1; done; \
	    [ "$$rc" -eq 0 ] || exit 1; \
	fi; \
	echo "check-common: all steps passed ($(CARGO_CHECK_STEPS) $(NONCARGO_CHECK_STEPS))"

# Install the scrub binary and point git at the tracked hooks. Idempotent.
# Asserts the scrub gate is actually live on this clone: template shims in
# sync, git hooks activated, installed binary not stale. See scrub/selfcheck.sh.
scrub-selfcheck:
	@./scrub/selfcheck.sh

# Canonical release-gate sweep: the tree must be free of disallowed strings.
# Invokes the installed brenn-scrub (the same binary the git hooks use;
# scrub-selfcheck asserts it is not stale). The exclude list is now empty: the
# private instance-config TOMLs and the CI workflow that carried private
# git-dependency URLs have moved to the brenn-ops annex, and the git deps are
# repointed to public sources. A prefix that matches no tracked file panics, so
# a stale exclude fails this target loudly rather than silently passing.
# TODO(scrub-tree-auto-gate): nothing runs this automatically, so the green-tree
# invariant and the stale-exclude panic only fire when someone remembers to
# invoke it. Wiring it into check-common/check-ci needs a decision on the CI
# binary (CI runs check-ci without installing brenn-scrub) or a hermetic
# invocation.
scrub-tree:
	brenn-scrub tree

setup-hooks:
	cargo install --path scrub
	git config core.hooksPath .githooks
	@rm -f .git/hooks/pre-commit
	@command -v gitleaks >/dev/null 2>&1 || { \
	    echo "gitleaks not found on PATH."; \
	    echo "Install the pinned release from https://github.com/gitleaks/gitleaks/releases"; \
	    echo "(version pin: see PINNED_VERSION in scrub/src/gitleaks.rs)"; \
	}
	@echo "setup-hooks: done."

# CI check: check-common only. cargo-deny is NOT installed in CI.
check-ci: check-common

# Full pre-commit check: check-common + cargo-deny gate (local only).
# cargo-deny must be installed locally: cargo install --locked cargo-deny
check: check-common
	@if [ -n "$(V)" ]; then \
	    $(MAKE) xtask-deny || { echo "FAILED: xtask-deny"; exit 1; }; \
	else \
	    tmp=$$(mktemp); \
	    if ! $(MAKE) xtask-deny >"$$tmp" 2>&1; then \
	        echo "FAILED: xtask-deny"; cat "$$tmp"; rm -f "$$tmp"; exit 1; \
	    fi; \
	    rm -f "$$tmp"; \
	fi; \
	echo "check: all steps passed ($(CARGO_CHECK_STEPS) $(NONCARGO_CHECK_STEPS) xtask-deny)"

# Guard the crate split: only the thin brenn bin crate may reference
# BRENN_BUILD_ID. The whole point of the thin-brenn / brenn-server split is that
# the heavily tested library — and every crate it depends on — does not vary
# with the build id, so their test binaries stay cache hits across commits. A
# stray env!/option_env!/std::env::var or a reintroduced build.rs directive in
# any crate below brenn (brenn-lib, the const's historical home, is the most
# likely habit-driven reintroduction point) would silently evaporate that win
# with no compile error or test failure — only make check drifting back to ~45s
# (worse the deeper the crate). This turns that regression into a hard failure.
# Scoped to the whole tree minus the brenn/ bin crate (its build.rs and
# build_info.rs legitimately bake the value in).
build-id-leaf-gate:
	@if [ ! -d brenn-server ]; then \
	    echo "ERROR: build-id-leaf-gate could not run: brenn-server/ not found."; \
	    exit 1; \
	fi; \
	grep -rn --include='*.rs' --include='*.toml' \
	    --exclude-dir=target --exclude-dir=node_modules --exclude-dir=brenn \
	    'BRENN_BUILD_ID' .; \
	status=$$?; \
	if [ "$$status" -eq 0 ]; then \
	    echo "ERROR: only the brenn bin crate may reference BRENN_BUILD_ID (see thin-brenn crate split)."; \
	    exit 1; \
	elif [ "$$status" -ne 1 ]; then \
	    echo "ERROR: build-id-leaf-gate could not run (grep exit $$status)."; \
	    exit 1; \
	fi

# Build everything (Rust + TypeScript, including type generation).
build: types frontend wasm-components surface-wasm
	cargo build

# Production release build.
release: types frontend wasm-components surface-wasm
	cargo build --release

# Static musl release build (for CI/deployment).
# The surface cdylib crates (shell + every surface/components/* bundle, i.e.
# SURFACE_WASM_CRATES) are browser-only wasm artifacts produced by the
# surface-wasm pipeline above and are not linked into any host binary. A
# non-wasm target such as musl cannot produce a cdylib, so exclude them from the
# host workspace build. Deriving the exclude list from SURFACE_WASM_CRATES keeps
# this correct automatically as new components are added (glob-discovered).
release-musl: types frontend wasm-components surface-wasm
	cargo build --release --target x86_64-unknown-linux-musl --workspace $(addprefix --exclude ,$(SURFACE_WASM_CRATES))

fmt:
	cargo fmt -- --check

clippy:
	cargo clippy $(Q) --all-targets -- -D warnings

# WASM clippy gate for the surface shell + client + every surface component
# crate, compiled for wasm32. Keeps the browser build green continuously instead
# of discovering rot when the real build depends on it. Needs the
# wasm32-unknown-unknown target (rust-toolchain.toml), not wasm-bindgen-cli.
# SURFACE_COMPONENT_CRATES is discovered from surface/components/* below.
#
# Two invocations, and the split is load-bearing:
#   1. --lib across every surface wasm crate. The kernel's protocol-core unit
#      tests build and run natively under `cargo test`, so its native test
#      targets are not wanted here.
#   2. --all-targets scoped to exactly the two crates carrying wasm-bindgen-test
#      suites (the kernel's dom/entry suites and component-support). `make
#      surface-wasm-test` (browser + driver) is the only thing that *runs* them,
#      and it is not in CARGO_CHECK_STEPS, so without this line the suites had no
#      compile gate at all — and a suite that does not compile cannot fail. The
#      kernel's tokio-bearing test modules are all `cfg(not(target_arch =
#      "wasm32"))`, so --all-targets under the wasm target compiles them out and
#      never reaches for the native-only dev-deps.
surface-wasm-check:
	cargo clippy $(Q) --target wasm32-unknown-unknown -p brenn-surface-kernel -p brenn-surface-component-support $(addprefix -p ,$(SURFACE_COMPONENT_CRATES)) --lib -- -D warnings
	cargo clippy $(Q) --target wasm32-unknown-unknown -p brenn-surface-kernel -p brenn-surface-component-support -p brenn-meeting --all-targets -- -D warnings

# Surface browser bundles: the wasm-bindgen pipeline for the shell and every
# component crate under surface/components/*. Unlike the WASI component rules
# below (wasm-tools component new), this emits wasm-bindgen ES-module glue
# (--target web) — the .js loader + _bg.wasm the browser imports directly.
# Artifacts land at the stable surface/dist/ path (gitignored) and are served
# no-cache by the surface asset handler.
#
# The wasm-bindgen crate and the wasm-bindgen-cli must be the exact same version.
# WASM_BINDGEN_PIN is read from the [workspace.dependencies] pin in Cargo.toml so
# the CLI-version preflight below can never drift from the crate pin. Shares
# WASM_COMPONENTS_TARGET with the component rules for a warm shared dep cache.
SURFACE_DIST := surface/dist
WASM_BINDGEN_PIN := $(shell sed -n 's/^wasm-bindgen = "=\(.*\)"/\1/p' Cargo.toml)

# Component crates are discovered from surface/components/*/Cargo.toml, so a new
# component builds with no Makefile edit. Directory name <kind> maps to crate
# brenn-<kind> and wasm-bindgen artifact brenn_<kind with - -> _> (the frozen
# naming convention in brenn-surface-contract).
# surface/chrome is the in-tree default chrome: an ordinary contract-v1 dom
# component that happens to live beside surface/components/ (dir <kind>=chrome ->
# crate brenn-chrome, artifact brenn_chrome), so it rides every component rule
# below by joining this discovered list.
SURFACE_COMPONENT_DIRS := $(patsubst %/,%,$(dir $(wildcard surface/components/*/Cargo.toml))) surface/chrome
SURFACE_COMPONENT_CRATES := $(foreach d,$(SURFACE_COMPONENT_DIRS),brenn-$(notdir $(d)))
SURFACE_WASM_CRATES := brenn-surface-kernel $(SURFACE_COMPONENT_CRATES)
SURFACE_WASM_JS := $(SURFACE_DIST)/brenn_surface_kernel.js \
    $(foreach d,$(SURFACE_COMPONENT_DIRS),$(SURFACE_DIST)/brenn_$(subst -,_,$(notdir $(d))).js)

# Per-kind documentation sidecars: a component crate may ship a help.md and/or
# schema.json next to its Cargo.toml. The surface self-description publisher reads
# them from SURFACE_DIST under the frozen brenn_<kind_underscored> naming, so the
# build copies each verbatim into dist. Only crates that actually ship a sidecar
# contribute a target (guarded by $(wildcard)), so a component with no docs is
# fine.
SURFACE_SIDECARS := $(foreach d,$(SURFACE_COMPONENT_DIRS),\
    $(if $(wildcard $(d)/help.md),$(SURFACE_DIST)/brenn_$(subst -,_,$(notdir $(d))).help.md)\
    $(if $(wildcard $(d)/schema.json),$(SURFACE_DIST)/brenn_$(subst -,_,$(notdir $(d))).schema.json))

# One copy rule per component dir (generated), mapping the crate's source sidecar
# to its dist name (dir <kind> -> brenn_<kind with - -> _>).
define SURFACE_SIDECAR_RULES
$(SURFACE_DIST)/brenn_$(subst -,_,$(notdir $(1))).help.md: $(1)/help.md
	mkdir -p $(SURFACE_DIST)
	cp $$< $$@
$(SURFACE_DIST)/brenn_$(subst -,_,$(notdir $(1))).schema.json: $(1)/schema.json
	mkdir -p $(SURFACE_DIST)
	cp $$< $$@
endef
$(foreach d,$(SURFACE_COMPONENT_DIRS),$(eval $(call SURFACE_SIDECAR_RULES,$(d))))

# Prune orphaned sidecars before publishing: any dist sidecar not in the current
# expected set (its source help.md/schema.json was deleted, or a component was
# renamed) is removed, so the self-description publisher never serves stale docs
# from an incremental build. Order-independent with the copy rules — the pruned
# set (files not in SURFACE_SIDECARS) and the copied set (files in it) are
# disjoint by construction, so parallel make ordering is irrelevant.
surface-sidecar-prune:
	@for f in $(wildcard $(SURFACE_DIST)/brenn_*.help.md) $(wildcard $(SURFACE_DIST)/brenn_*.schema.json); do \
	    case " $(SURFACE_SIDECARS) " in \
	        *" $$f "*) ;; \
	        *) echo "pruning orphaned surface sidecar $$f"; rm -f "$$f" ;; \
	    esac; \
	done

# The full Rust source closure across all built crates, tracked by content
# (recursive find) so a module nested any depth still dirties the build stamp.
SURFACE_WASM_SRCS := $(shell find surface/kernel/src surface/proto/src surface/component-support/src brenn-envelope/src surface/components surface/chrome/src -name '*.rs')

WASM_COMPONENTS_RELEASE := $(WASM_COMPONENTS_TARGET)/wasm32-unknown-unknown/release
# One shared cargo build produces every crate's .wasm; a stamp records it so N
# artifacts don't each retrigger a full build. Then one wasm-bindgen run per
# artifact turns each .wasm into its browser bundle.
SURFACE_WASM_STAMP := $(WASM_COMPONENTS_TARGET)/.surface-wasm-build.stamp

surface-wasm: surface-sidecar-prune $(SURFACE_WASM_JS) $(SURFACE_SIDECARS) surface-transpile

# Surface processor assets: `abi = "processor"` kinds are brenn:processor
# component-model artifacts — the same artifacts [[wasm_consumer]] blocks host
# backend-side — transpiled by jco into browser-loadable ES modules.
#
# SURFACE_PROCESSOR_KINDS names the kinds whose artifacts are transpiled for
# surface hosting; SURFACE_PROCESSOR_ARTIFACT_<kind> maps each to its component
# artifact. This is an explicit build-time list (like WASM_*_SRC/OUT above), not
# a wildcard or a read of server config: adding a surface-hostable processor is
# the same mechanical Makefile edit as adding a backend fixture.
SURFACE_PROCESSOR_KINDS := processor-transplant
SURFACE_PROCESSOR_ARTIFACT_processor-transplant := $(WASM_PROCESSOR_TRANSPLANT_OUT)

# jco version pin, read from surface/package.json so the preflight can never
# drift from the dependency the lockfile installs.
JCO_PIN := $(shell sed -n 's/.*"@bytecodealliance\/jco": "\(.*\)".*/\1/p' surface/package.json)
JCO_NODE_MAJOR_MIN := 20

# --instantiation async is load-bearing: it makes the emitted module export an
# `instantiate(getCoreModule, imports)` function rather than instantiating at
# module scope, which is what one-compiled-module-per-kind /
# one-instantiation-per-instance requires. The source artifact is copied beside
# the output so boot validation verifies provenance against the actual bytes,
# and the manifest is written last (it lists the files it sits among).
define SURFACE_PROCESSOR_RULES
$(SURFACE_DIST)/processor/$(1)/manifest.json: $(SURFACE_PROCESSOR_ARTIFACT_$(1)) surface/emit-processor-manifest.sh | jco-preflight
	rm -rf $(SURFACE_DIST)/processor/$(1)
	mkdir -p $(SURFACE_DIST)/processor/$(1)
	cd surface && npx jco transpile ../$$< --instantiation async --name $(1) --out-dir ../$(SURFACE_DIST)/processor/$(1)
	cp $$< $(SURFACE_DIST)/processor/$(1)/$(1).component.wasm
	surface/emit-processor-manifest.sh $(1) $$< $(SURFACE_DIST)/processor/$(1) $(JCO_PIN)
endef
$(foreach k,$(SURFACE_PROCESSOR_KINDS),$(eval $(call SURFACE_PROCESSOR_RULES,$(k))))

surface-transpile: $(foreach k,$(SURFACE_PROCESSOR_KINDS),$(SURFACE_DIST)/processor/$(k)/manifest.json)

# Mirrors wasm-bindgen-preflight: verifies node is present and new enough and
# that the installed jco matches the pin, failing with the command that fixes it
# rather than letting a stale toolchain emit assets boot validation then rejects.
jco-preflight: surface/node_modules
	@test -n "$(JCO_PIN)" || { echo "ERROR: could not extract the jco pin from surface/package.json (format changed?)"; exit 1; }
	@command -v node >/dev/null 2>&1 || { echo "ERROR: node not found on PATH; jco needs node >= $(JCO_NODE_MAJOR_MIN)"; exit 1; }
	@major=$$(node -p "process.versions.node.split('.')[0]"); \
	if [ "$$major" -lt $(JCO_NODE_MAJOR_MIN) ]; then \
	    echo "ERROR: node $$major is below the surface/package.json engines floor ($(JCO_NODE_MAJOR_MIN)); upgrade node"; \
	    exit 1; \
	fi
	@have=$$(cd surface && node -p "require('./node_modules/@bytecodealliance/jco/package.json').version" 2>/dev/null || true); \
	if [ "$$have" != "$(JCO_PIN)" ]; then \
	    echo "ERROR: installed jco '$$have' != pinned $(JCO_PIN); reinstall with: cd surface && npm ci"; \
	    exit 1; \
	fi

# Verifies the installed wasm-bindgen-cli matches the crate pin before any
# wasm-bindgen invocation. Order-only prerequisite of the bundle rule so it
# never forces a rebuild but always guards a stale/absent CLI.
wasm-bindgen-preflight:
	@test -n "$(WASM_BINDGEN_PIN)" || { echo "ERROR: could not extract wasm-bindgen pin from Cargo.toml [workspace.dependencies] (format changed?)"; exit 1; }
	@command -v wasm-bindgen >/dev/null 2>&1 || { echo "ERROR: wasm-bindgen not found on PATH; install with: cargo install --locked wasm-bindgen-cli --version $(WASM_BINDGEN_PIN)"; exit 1; }
	@have=$$(wasm-bindgen --version | awk '{print $$2}'); \
	if [ "$$have" != "$(WASM_BINDGEN_PIN)" ]; then \
	    echo "ERROR: wasm-bindgen-cli $$have != pinned $(WASM_BINDGEN_PIN); reinstall with: cargo install --locked wasm-bindgen-cli --version $(WASM_BINDGEN_PIN)"; \
	    exit 1; \
	fi

# Prereqs include the workspace root Cargo.toml (the wasm-bindgen pin + all
# workspace deps) and Cargo.lock (transitive versions) so a dependency bump —
# including a pin bump — retriggers the rebuild instead of silently serving a
# stale bundle.
$(SURFACE_WASM_STAMP): $(SURFACE_WASM_SRCS) \
      surface/kernel/Cargo.toml surface/proto/Cargo.toml surface/component-support/Cargo.toml brenn-envelope/Cargo.toml \
      $(foreach d,$(SURFACE_COMPONENT_DIRS),$(d)/Cargo.toml) \
      Cargo.toml Cargo.lock
	CARGO_TARGET_DIR=$(WASM_COMPONENTS_TARGET) cargo build --release --target wasm32-unknown-unknown $(addprefix -p ,$(SURFACE_WASM_CRATES))
	mkdir -p $(dir $@)
	touch $@

# One wasm-bindgen run per artifact. The stamp guarantees the .wasm exists; the
# order-only preflight guarantees a matching CLI.
$(SURFACE_DIST)/%.js: $(SURFACE_WASM_STAMP) | wasm-bindgen-preflight
	mkdir -p $(SURFACE_DIST)
	wasm-bindgen --target web --out-dir $(SURFACE_DIST) $(WASM_COMPONENTS_RELEASE)/$*.wasm

# Browser-level wasm unit tests for the surface shell + component-support
# (wasm-bindgen-test, headless browser via chromedriver/geckodriver).
# Not part of local `make check`: it needs a WebDriver browser driver, which
# contributors are not asked to install. surface-wasm-check's --all-targets line
# type-checks these suites on every check, so they cannot rot between runs.
# Run manually when touching surface/kernel/src/{dom,entry}.rs or
# surface/component-support.
# NO_HEADLESS=1 passes through to the runner for a visible browser when debugging.
#
# TODO(surface-wasm-test-in-ci): CI should run this — a type-checked suite that
# never runs answers no behavioral question. Blocked on installing chromedriver
# on the Forgejo runner host (not cargo-installable, so no workflow step can do
# it); landing the check-ci step before that provisioning turns main red.
surface-wasm-test: wasm-bindgen-preflight
	@command -v wasm-bindgen-test-runner >/dev/null 2>&1 || { echo "ERROR: wasm-bindgen-test-runner not found; it ships with wasm-bindgen-cli: cargo install --locked wasm-bindgen-cli --version $(WASM_BINDGEN_PIN)"; exit 1; }
	@command -v chromedriver >/dev/null 2>&1 || command -v geckodriver >/dev/null 2>&1 || { echo "ERROR: need chromedriver or geckodriver on PATH (Fedora: dnf install chromedriver)"; exit 1; }
	CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test-runner \
	    cargo test --target wasm32-unknown-unknown -p brenn-surface-kernel -p brenn-surface-component-support -p brenn-meeting --lib
	CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test-runner \
	    cargo test --target wasm32-unknown-unknown -p brenn-surface-component-support --test prebind_panic

# Run the workspace test suite via cargo-nextest with an incremental
# binary-hash result cache (xtask test owns both the nextest run and the cache;
# it also runs doctests, which nextest does not). xtask fails fast if nextest is
# absent, so no Makefile-side preflight is needed; an incompatible version fails
# the run naturally.
# BRENN_TEST_CACHE=0 disables the cache; V=1 streams live output.
# surface-transpile is a real prerequisite, not a convenience: the emitter-vs-
# extractor parity test reads the transpiled tree's manifest.json and fails
# (never skips) if it is absent, so the transpile must have run for that pin to
# be asserted at all. Stamp-gated, so a warm tree is a no-op.
test: wasm-components surface-transpile
	cargo run -p xtask -- test

# Run Python unit tests for noop_mcp.py. PYTHONDONTWRITEBYTECODE=1 keeps CPython
# from creating __pycache__/ and its temp-then-replace .pyc, so this step never
# writes into the tree while the check lanes walk it.
test-py:
	PYTHONDONTWRITEBYTECODE=1 python3 -m unittest noop_mcp_test

# Run TypeScript tests (vitest).
#
# surface-transpile is a real prerequisite, not a convenience: the transplant
# parity suite loads the jco-transpiled processor tree and fails (never skips) if
# it is absent, so the transpile must have run for the surface half of the
# transplant invariant to be asserted at all. Stamp-gated, so a warm tree is a
# no-op.
test-ts: surface-transpile
	cd frontend && npx vitest run

# Generate TypeScript types from Rust via ts-rs (cargo test runs the export).
types:
	cargo test -p brenn-lib ws_types::tests::ts_rs_export
	cargo test -p brenn-server upload::tests::ts_rs_export

# Regenerate frontend/src/styles/frontmatter.generated.ts from the Rust
# source of truth (brenn-lib/src/frontmatter_css.rs). Drift between
# Rust and frontend would otherwise be invisible at build time.
frontend-css:
	cargo run --quiet -p brenn-cli -- emit-frontmatter-css --out frontend/src/styles/frontmatter.generated.ts

# Type-check TypeScript (no emit — esbuild handles bundling).
# Main app and service worker have separate tsconfigs (DOM vs WebWorker libs).
tsc:
	cd frontend && npx tsc --noEmit
	cd frontend && npx tsc --noEmit -p tsconfig.sw.json

# Bundle TypeScript + Lit into a single JS file, copy CSS + PWA assets.
# `--define:globalThis.__BRENN_BUILD_ID__` injects BRENN_BUILD_ID as a
# JS string literal; TS reads it via build-info.ts, and
# frontend/vitest.config.ts mirrors the same define for tests.
frontend: types frontend-css frontend/node_modules
	cd frontend && npx esbuild src/main.ts --bundle --format=esm --outfile=dist/main.js --sourcemap --define:globalThis.__BRENN_BUILD_ID__='"$(BRENN_BUILD_ID)"'
	cd frontend && npx esbuild src/sw.ts --bundle --format=esm --outfile=dist/sw.js --define:globalThis.__BRENN_BUILD_ID__='"$(BRENN_BUILD_ID)"'
	cd frontend && npx esbuild src/nav-on-message.ts --bundle --format=esm --outfile=dist/nav-on-message.js --define:globalThis.__BRENN_BUILD_ID__='"$(BRENN_BUILD_ID)"'
	# The surface bootstrap takes its build id from the page meta tag, not a
	# compile-time define, so it needs no __BRENN_BUILD_ID__ injection.
	cd frontend && npx esbuild src/surface.ts --bundle --format=esm --outfile=dist/surface.js --sourcemap
	cp frontend/src/app.css frontend/dist/app.css
	cp frontend/src/surface.css frontend/dist/surface.css
	# Skin packs + vendored fonts, served at /static/skins/<name>.css and
	# /static/skins/fonts/*.woff2 (the surface page handler's skin <link> and
	# each pack's @font-face resolve here). The whole tree is copied verbatim.
	rm -rf frontend/dist/skins
	cp -R frontend/skins frontend/dist/skins
	cp frontend/src/file-view-copy.js frontend/dist/file-view-copy.js
	# Manifest + icons are also compiled into the brenn binary
	# (see brenn/src/routes/statics.rs); these copies support standalone
	# static-file preview during dev.
	cp frontend/src/manifest.webmanifest frontend/dist/manifest.webmanifest
	cp frontend/src/icon-192.png frontend/dist/icon-192.png
	cp frontend/src/icon-512.png frontend/dist/icon-512.png

frontend/node_modules: frontend/package-lock.json
	cd frontend && npm ci

e2e/node_modules: e2e/package-lock.json
	cd e2e && npm ci

surface/node_modules: surface/package-lock.json
	cd surface && npm ci

# Materialize all node dependency trees. check-common runs this in the foreground
# before forking background steps so a lazy `npm ci` (triggered by a changed
# package-lock) cannot delete and reinstall node_modules concurrently with a
# tsc/vitest run reading out of the same directory.
node-deps: frontend/node_modules e2e/node_modules surface/node_modules

# Fail the build on known npm advisories (full audit, dev deps included).
# The node_modules prerequisites ensure a clean checkout installs deps before
# auditing, so this stays green on checkouts that never run `make e2e`.
npm-audit: frontend/node_modules e2e/node_modules surface/node_modules
	cd frontend && npm audit
	cd e2e && npm audit
	cd surface && npm audit

DEV_PIDFILE := .dev-server.pid

# Hermetic e2e config server settings, mirrored from brenn.e2e.toml.
E2E_BIN := ./target/debug/brenn
E2E_BASE_URL := http://127.0.0.1:3100

# Browser-level end-to-end tests (Playwright). Deliberately NOT part of
# `make check`: needs installed Playwright browsers and a live server. Fresh DB
# every run (rm -rf target/e2e) keeps it hermetic. Mints an invite via the
# built binary, starts the hermetic server backgrounded (launchdev pattern —
# no output redirection, which would hang the pipe against the backgrounded
# process), polls the login page until ready (checking server liveness first
# each iteration so a bind failure is reported, not masked by a foreign
# listener), runs the specs with the base URL and invite exported, and always
# stops the server (trap), propagating the
# test exit code. Chromium is the one genuine one-time setup step; a missing
# browser fails fast with the install command before any server starts.
e2e: build e2e/node_modules
	@cd e2e && node -e "const{chromium}=require('@playwright/test');const fs=require('fs');const p=chromium.executablePath();if(!fs.existsSync(p)){console.error('ERROR: Playwright chromium browser not installed. Run: cd e2e && npx playwright install chromium');process.exit(1);}"
	@rm -rf target/e2e
	@mkdir -p target/e2e
	@set -e; \
	if curl -sf -o /dev/null $(E2E_BASE_URL)/auth/login 2>/dev/null; then \
	    echo "ERROR: $(E2E_BASE_URL) is already serving before we started — a leaked e2e server or a port clash on 3100. Kill it before running make e2e."; exit 1; \
	fi; \
	invite=$$($(E2E_BIN) --config brenn.e2e.toml invite); \
	$(E2E_BIN) --config brenn.e2e.toml serve & \
	srv=$$!; \
	trap 'kill $$srv 2>/dev/null || true' EXIT INT TERM; \
	echo "e2e: server PID $$srv; polling $(E2E_BASE_URL)/auth/login ..."; \
	ready=0; \
	for i in $$(seq 1 60); do \
	    kill -0 $$srv 2>/dev/null || { echo "ERROR: e2e server exited before becoming ready"; exit 1; }; \
	    if curl -sf -o /dev/null $(E2E_BASE_URL)/auth/login; then ready=1; break; fi; \
	    sleep 1; \
	done; \
	[ "$$ready" -eq 1 ] || { echo "ERROR: e2e server not ready within 60s"; exit 1; }; \
	cd e2e && BRENN_E2E_BASE_URL=$(E2E_BASE_URL) BRENN_E2E_INVITE=$$invite npx playwright test

# Start the dev server in the background. Builds first.
launchdev: build
	@if [ -f $(DEV_PIDFILE) ] && kill -0 $$(cat $(DEV_PIDFILE)) 2>/dev/null; then \
		echo "Dev server already running (PID $$(cat $(DEV_PIDFILE)))"; \
	else \
		cargo run --bin brenn -- --config brenn.dev.toml serve & \
		echo $$! > $(DEV_PIDFILE); \
		echo "Dev server started (PID $$!)"; \
		sleep 1; \
	fi

# Stop the dev server.
stopdev:
	@if [ -f $(DEV_PIDFILE) ]; then \
		kill $$(cat $(DEV_PIDFILE)) 2>/dev/null && echo "Dev server stopped" || echo "Dev server not running"; \
		rm -f $(DEV_PIDFILE); \
	else \
		echo "No PID file found"; \
	fi

# Build WASM component artifacts and copy to the stable host-test path.
# CARGO_TARGET_DIR is set explicitly (see WASM_COMPONENTS_TARGET above) so all
# component crates share one dep cache. This defeats CI's exported
# CARGO_TARGET_DIR identically to the old env -u approach while also letting
# shared deps compile once across all fixtures on a cold build.
#
# wasm32-unknown-unknown: avoids Rust std WASI imports. The wasip1 panic->stderr
# path pulls wasi:cli/environment; the host wasmtime linker has no WASI provider.
# All component crates must build with this target for WASI-free output.
#
# Adding a new DEPLOYABLE component? Also list its artifact basename in
# brenn-wasm/deployed-components.txt, or CI/deploy.sh will build it but never
# ship it. (Test-only components stay out of that manifest.)
# Test-only (NOT in deployed-components.txt):
#   WASM_PROCESSOR_EXHAUST_OUT, WASM_PROCESSOR_DUAL_OUT, WASM_PROCESSOR_STORE_RT_OUT,
#   WASM_PROCESSOR_MEM_EXHAUST_OUT, WASM_PROCESSOR_LOG_OUT, WASM_PROCESSOR_MULTIPORT_OUT,
#   WASM_PROCESSOR_MQTT_TEST_OUT — fixture components for integration tests only.
# WASM_PROCESSOR_DEMO_OUT (brenn_processor_demo.wasm) IS deployed — listed in
#   deployed-components.txt.

# $(call wasm_component_rule,<src-dir>,<out-path>,<wit-file>)
# Generates one Make rule building a WASM component from its source crate.
# $(notdir $(2)) derives the artifact basename from the output path — this equals
# the crate's cdylib output name for all 9 components (verified in exploration).
# Inside define/eval: $$ defers to recipe-expansion; $$$$ yields a literal shell $.
#
# Build path (no cargo-component):
#   1. wit-bindgen rust brenn-wasm/wit/<wit-file> → <world>.rs in src/, renamed
#      to bindings.rs (wit-bindgen-cli 0.58 derives output filename from world name).
#      NOTE: this overwrites src/bindings.rs in-place on every rebuild. The overwrite
#      is always identical bytes (same generator, same WIT), so cargo does not recompile.
#      The xtask check-wit drift gate polices committed-vs-generated equality. If cargo
#      build or wasm-tools fail after the mv, bindings.rs has already been overwritten;
#      restore with: git checkout -- <crate>/src/bindings.rs
#   2. cargo build --release --target wasm32-unknown-unknown (plain cargo, no component).
#   3. wasm-tools component new: wraps the raw cdylib into a WIT component.
#      The 0.58 bindings self-embed the component-type section so no adapter is needed.
define wasm_component_rule
$(2): $(1)/src/lib.rs $(1)/src/bindings.rs $(1)/Cargo.toml brenn-wasm/wit/$(3)
	mkdir -p $$(dir $(2))
	@command -v wit-bindgen >/dev/null 2>&1 || { echo "ERROR: wit-bindgen not found on PATH; install with: cargo install --locked wit-bindgen-cli --version 0.58.0"; exit 1; }
	wit-bindgen rust brenn-wasm/wit/$(3) --runtime-path wit_bindgen_rt --out-dir $(1)/src
	mv $(1)/src/$(patsubst %.wit,%,$(3)).rs $(1)/src/bindings.rs
	cd $(1) && CARGO_TARGET_DIR=$(WASM_COMPONENTS_TARGET) cargo build --release --target wasm32-unknown-unknown
	@command -v wasm-tools >/dev/null 2>&1 || { echo "ERROR: wasm-tools not found on PATH; install with: cargo install --locked wasm-tools --version 1.249.0"; exit 1; }
	wasm-tools component new $(WASM_COMPONENTS_TARGET)/wasm32-unknown-unknown/release/$$(notdir $(2)) -o $(2)
	# TODO(xtask-wasi-macro-cleanup): this WASI grep duplicates xtask check-wit; remove once xtask check-wit is proven in CI.
	@WIT=$$$$(wasm-tools component wit $(2)); \
	if echo "$$$$WIT" | grep -q 'import wasi:'; then \
	    echo "ERROR: $(2) imports wasi:* — WASI must not appear in the component"; \
	    echo "$$$$WIT" | grep 'import wasi:'; \
	    exit 1; \
	fi
endef

# $(call wasm_guest_component_rule,<src-dir>,<out-path>)
# Generates one Make rule building a WASM component from a brenn-guest-based crate.
# These crates use brenn-guest (which owns the WIT bindings via wit-bindgen::generate!)
# and do NOT have a committed bindings.rs or [package.metadata.component] table.
# Build path: plain `cargo build` (no cargo-component) → core WASM module, then
# `wasm-tools component new` to wrap it into a component (no WASI adapter needed;
# these components import only brenn:processor WIT, not wasi:*).
# Prerequisites include the full path-dep closure: brenn-guest + brenn-envelope files.
# Glob prerequisites ($(wildcard ...)) ensure new src/*.rs modules added to any of
# these crates automatically dirty the artifact — no stale WASM after source splits.
define wasm_guest_component_rule
$(2): $(wildcard $(1)/src/*.rs) $(1)/Cargo.toml \
      $(wildcard brenn-wasm/guest/src/*.rs) brenn-wasm/guest/Cargo.toml \
      $(wildcard brenn-envelope/src/*.rs) brenn-envelope/Cargo.toml \
      brenn-wasm/wit/processor.wit
	mkdir -p $$(dir $(2))
	@command -v wasm-tools >/dev/null 2>&1 || { echo "ERROR: wasm-tools not found on PATH; install with: cargo install --locked wasm-tools --version 1.249.0"; exit 1; }
	cd $(1) && CARGO_TARGET_DIR=$(WASM_COMPONENTS_TARGET) cargo build --release --target wasm32-unknown-unknown
	wasm-tools component new $(WASM_COMPONENTS_TARGET)/wasm32-unknown-unknown/release/$$(notdir $(2)) -o $(2)
	# TODO(xtask-wasi-macro-cleanup): this WASI grep duplicates xtask check-wit; remove once xtask check-wit is proven in CI.
	@WIT=$$$$(wasm-tools component wit $(2)); \
	if echo "$$$$WIT" | grep -q 'import wasi:'; then \
	    echo "ERROR: $(2) imports wasi:* — WASI must not appear in the component"; \
	    echo "$$$$WIT" | grep 'import wasi:'; \
	    exit 1; \
	fi
endef

wasm-components: $(WASM_COMPONENT_OUTS)

$(eval $(call wasm_component_rule,$(WASM_REPLAY_SRC),$(WASM_REPLAY_OUT),replay.wit))
# Standalone extra-prerequisite for replay (only): brenn-cal is a path dep of the
# replay component but is not covered by wasm_component_rule's generic prereqs.
# Fix in passing per design §2.5. Not a macro-body edit (that would rebuild all
# eleven components on any brenn-cal change); a targeted line here rebuilds only
# the one artifact that actually depends on brenn-cal.
$(WASM_REPLAY_OUT): $(wildcard brenn-cal/src/*.rs) brenn-cal/Cargo.toml
$(eval $(call wasm_component_rule,$(WASM_FAULT_SRC),$(WASM_FAULT_OUT),replay.wit))
$(eval $(call wasm_component_rule,$(WASM_GENERIC_SRC),$(WASM_GENERIC_OUT),replay.wit))
$(eval $(call wasm_guest_component_rule,$(WASM_PROCESSOR_DEMO_SRC),$(WASM_PROCESSOR_DEMO_OUT)))
$(eval $(call wasm_component_rule,$(WASM_PROCESSOR_EXHAUST_SRC),$(WASM_PROCESSOR_EXHAUST_OUT),processor.wit))
$(eval $(call wasm_guest_component_rule,$(WASM_PROCESSOR_DUAL_SRC),$(WASM_PROCESSOR_DUAL_OUT)))
$(eval $(call wasm_guest_component_rule,$(WASM_PROCESSOR_STORE_RT_SRC),$(WASM_PROCESSOR_STORE_RT_OUT)))
$(eval $(call wasm_component_rule,$(WASM_PROCESSOR_MEM_EXHAUST_SRC),$(WASM_PROCESSOR_MEM_EXHAUST_OUT),processor.wit))
$(eval $(call wasm_guest_component_rule,$(WASM_PROCESSOR_LOG_SRC),$(WASM_PROCESSOR_LOG_OUT)))
$(eval $(call wasm_guest_component_rule,$(WASM_PROCESSOR_MULTIPORT_SRC),$(WASM_PROCESSOR_MULTIPORT_OUT)))
$(eval $(call wasm_guest_component_rule,$(WASM_PROCESSOR_CONFIG_SRC),$(WASM_PROCESSOR_CONFIG_OUT)))
$(eval $(call wasm_guest_component_rule,$(WASM_PROCESSOR_TRANSPLANT_SRC),$(WASM_PROCESSOR_TRANSPLANT_OUT)))
$(eval $(call wasm_component_rule,$(WASM_PROCESSOR_MQTT_TEST_SRC),$(WASM_PROCESSOR_MQTT_TEST_OUT),processor.wit))
$(eval $(call wasm_component_rule,$(WASM_PROCESSOR_TOOL_TEST_SRC),$(WASM_PROCESSOR_TOOL_TEST_OUT),processor.wit))
$(eval $(call wasm_guest_component_rule,$(WASM_GIT_FORGE_PARSER_SRC),$(WASM_GIT_FORGE_PARSER_OUT)))
$(eval $(call wasm_guest_component_rule,$(WASM_GIT_SYNC_CONSUMER_SRC),$(WASM_GIT_SYNC_CONSUMER_OUT)))

# Assert that the WASI-import check inside wasm_component_rule AND
# wasm_guest_component_rule is live — i.e. the $$$$-escaping in the define/eval
# layer still produces a real shell $ at recipe execution time. Strategy: dry-run
# expand one recipe from each rule family (make -n) and grep for the two shell
# fragments that perform the check. Covers both independently: a future Makefile
# edit could break one escaping copy without affecting the other. wasm-tools need
# not be installed for this check — we only inspect the recipe text.
check-wasi-check-liveness:
	@ok=1; \
	for target in $(WASM_REPLAY_OUT) $(WASM_PROCESSOR_DEMO_OUT); do \
	    expanded=$$($(MAKE) -Bn $$target 2>&1); \
	    if ! echo "$$expanded" | grep -q 'wasm-tools component wit'; then \
	        echo "ERROR: check-wasi-check-liveness: $$target missing wasm-tools component wit — dollar-escaping may be broken"; \
	        ok=0; \
	    fi; \
	    if ! echo "$$expanded" | grep -q 'grep -q .import wasi:'; then \
	        echo "ERROR: check-wasi-check-liveness: $$target missing grep -q import wasi — dollar-escaping may be broken"; \
	        ok=0; \
	    fi; \
	done; \
	if [ "$$ok" -eq 1 ]; then \
	    echo "check-wasi-check-liveness: WASI check is live in both wasm_component_rule and wasm_guest_component_rule"; \
	fi; \
	[ "$$ok" -eq 1 ]

# Clippy for brenn-guest (wasm32-unknown-unknown target only — this crate
# is outside the main workspace and is not covered by the workspace `make clippy`).
# Uses the shared CARGO_TARGET_DIR so dependency compilation is warm after a full build.
# Note: `cargo check` is a strict subset of `cargo clippy`; no separate check step needed.
check-brenn-guest:
	cd brenn-wasm/guest && CARGO_TARGET_DIR=$(WASM_COMPONENTS_TARGET) cargo clippy --target wasm32-unknown-unknown -- -D warnings

clean:
	cargo clean
	rm -rf $(WASM_COMPONENTS_TARGET)
	rm -rf $(addsuffix /target,$(WASM_COMPONENT_SRCS))
	rm -rf brenn-wasm/target/components
	rm -rf frontend/dist/main.js frontend/dist/main.js.map frontend/dist/app.css frontend/dist/sw.js frontend/dist/manifest.webmanifest frontend/dist/icon-*.png frontend/dist/surface.css frontend/dist/skins
	rm -rf surface/dist

# Check that committed bindings.rs files are up to date with their WIT files.
# Saves the current files, regenerates via wit-bindgen-cli 0.58, diffs,
# and unconditionally restores the originals (trap ensures no state is lost
# even on failure). Never uses git checkout -- so uncommitted developer edits
# are preserved.
#
# For each raw crate: wit-bindgen rust <wit-path> → <world>.rs, renamed to
# bindings.rs (mirrors the drift gate in xtask check-wit and the build rule
# above — all three must use the same generator and rename logic).
# Install wit-bindgen-cli: cargo install --locked wit-bindgen-cli --version 0.58.0
check-wasm-bindings:
	@command -v wit-bindgen >/dev/null 2>&1 || { echo "ERROR: wit-bindgen not found on PATH; install with: cargo install --locked wit-bindgen-cli --version 0.58.0"; exit 1; }
	@tmpdir=$$(mktemp -d) && \
	trap 'for f in $(WASM_BINDINGS); do key=$$(echo "$$f" | tr "/" "_"); [ -f "$$tmpdir/$$key" ] && cp "$$tmpdir/$$key" "$$f"; done; \
	      rm -f $(WASM_REPLAY_SRC)/src/replay.rs $(WASM_FAULT_SRC)/src/replay.rs $(WASM_GENERIC_SRC)/src/replay.rs $(WASM_PROCESSOR_EXHAUST_SRC)/src/processor.rs $(WASM_PROCESSOR_MEM_EXHAUST_SRC)/src/processor.rs $(WASM_PROCESSOR_MQTT_TEST_SRC)/src/processor.rs $(WASM_PROCESSOR_TOOL_TEST_SRC)/src/processor.rs; \
	      rm -rf "$$tmpdir"' EXIT && \
	for f in $(WASM_BINDINGS); do key=$$(echo "$$f" | tr "/" "_"); cp "$$f" "$$tmpdir/$$key"; done && \
	for entry in \
	    "$(WASM_REPLAY_SRC):replay.wit" \
	    "$(WASM_FAULT_SRC):replay.wit" \
	    "$(WASM_GENERIC_SRC):replay.wit" \
	    "$(WASM_PROCESSOR_EXHAUST_SRC):processor.wit" \
	    "$(WASM_PROCESSOR_MEM_EXHAUST_SRC):processor.wit" \
	    "$(WASM_PROCESSOR_MQTT_TEST_SRC):processor.wit" \
	    "$(WASM_PROCESSOR_TOOL_TEST_SRC):processor.wit" \
	; do \
	    d=$${entry%%:*}; wit=$${entry##*:}; world=$${wit%.wit}; \
	    wit-bindgen rust brenn-wasm/wit/$$wit --runtime-path wit_bindgen_rt --out-dir $$d/src >/dev/null || exit 1; \
	    mv $$d/src/$$world.rs $$d/src/bindings.rs || { echo "ERROR: failed to rename $$d/src/$$world.rs to $$d/src/bindings.rs"; exit 1; }; \
	done && \
	fail=0 && \
	for f in $(WASM_BINDINGS); do \
	    key=$$(echo "$$f" | tr "/" "_"); \
	    if ! diff -q "$$f" "$$tmpdir/$$key" >/dev/null 2>&1; then \
	        diff -u "$$tmpdir/$$key" "$$f" || true; \
	        fail=1; \
	    fi; \
	done && \
	if [ "$$fail" -eq 1 ]; then \
	    echo "ERROR: WASM bindings are stale. Regenerate with: wit-bindgen rust <wit-file> --runtime-path wit_bindgen_rt --out-dir <crate>/src && mv <crate>/src/<world>.rs <crate>/src/bindings.rs"; \
	    exit 1; \
	fi
