// AUTO-GENERATED by `brenn-cli emit-frontmatter-css`. Do not edit.
// Source of truth: brenn-lib/src/frontmatter_css.rs
import { css } from "lit";

export const frontmatterStyles = css`
.fm-block {
  font-size: 0.9em;
  color: #a0a0b0;
  border-bottom: 1px solid #2a2a40;
  padding-bottom: 0.5rem;
  margin-bottom: 0.75rem;
}
.fm-list {
  display: grid;
  grid-template-columns: max-content 1fr;
  column-gap: 0.75rem;
  row-gap: 0.15rem;
  margin: 0;
  padding: 0;
}
.fm-row {
  display: contents;
}
.fm-list dt {
  font-weight: 600;
  color: #808098;
  margin: 0;
  padding: 0;
}
.fm-list dd {
  margin: 0;
  padding: 0;
  min-width: 0;
  word-break: normal;
}
.fm-md p {
  margin: 0;
}
.fm-sublist {
  list-style: none;
  padding-left: 0;
  margin: 0;
}
.fm-sublist li {
  margin: 0;
}
.fm-truncated {
  font-style: italic;
  color: #808098;
}
.fm-null {
  color: #6a6a8a;
  font-style: italic;
}
.fm-raw {
  font-family: "JetBrains Mono", "Fira Code", "Cascadia Code", monospace;
  font-size: 0.95em;
  color: #b0b0c0;
}
.fm-error {
  color: #c08080;
  border: 1px solid #c08080;
  padding: 0.5rem;
  margin-bottom: 0.75rem;
  border-radius: 3px;
}
.fm-error pre {
  margin: 0;
  white-space: pre-wrap;
}
`;
