#!/usr/bin/env bash
# Assert a committed generated file holds exactly the bytes Bazel generates.
#
# Usage: parity_check.sh <committed> <generated> <committed-label>
#
# Migration-window gate. The make lanes and the deploy path still read the
# committed copy, so the two generators have to agree byte for byte; when the
# committed copies go, so does this.
set -euo pipefail

if [ "$#" -ne 3 ]; then
    echo "usage: $0 <committed> <generated> <committed-label>" >&2
    exit 2
fi
committed="$1"
generated="$2"
label="$3"

for f in "$committed" "$generated"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: $f is not a regular file; the comparison would assert nothing."
        exit 1
    fi
done

if ! diff -u "$committed" "$generated"; then
    echo "ERROR: committed $label differs from the generated bytes"
    exit 1
fi
