#!/usr/bin/env bash
# Assert a directory of committed generated files matches a generated tree.
#
# Usage: tree_parity_check.sh <committed-dir> <generated-dir> <label>
#
# Set equality, not containment, in both directions: a type that stopped being
# exported leaves a committed file nothing generates, and a newly exported type
# arrives as a generated file nothing commits. Either way the frontend compiles
# against a set the backend no longer emits, which is the drift this pins.
set -euo pipefail

if [ "$#" -ne 3 ]; then
    echo "usage: $0 <committed-dir> <generated-dir> <label>" >&2
    exit 2
fi
committed="$1"
generated="$2"
label="$3"

for d in "$committed" "$generated"; do
    if [ ! -d "$d" ]; then
        echo "ERROR: $d is not a directory; the comparison would assert nothing."
        exit 1
    fi
done

# -L, because a sandboxed test's input trees and runfiles are staged as
# symlinks: an unfollowed walk finds no regular files and compares two empty
# sets, which passes over anything.
list() { (cd "$1" && find -L . -type f -printf '%P\n' | LC_ALL=C sort); }

committed_files="$(list "$committed")"
generated_files="$(list "$generated")"

if [ -z "$generated_files" ]; then
    echo "ERROR: $generated is empty; the generator produced nothing to compare."
    exit 1
fi

if [ "$committed_files" != "$generated_files" ]; then
    echo "ERROR: the committed $label file set differs from the generated one"
    diff -u <(echo "$committed_files") <(echo "$generated_files") \
        --label "committed ($committed)" --label "generated ($generated)" || true
    exit 1
fi

status=0
while IFS= read -r rel; do
    if ! diff -u "$committed/$rel" "$generated/$rel" \
        --label "committed $label/$rel" --label "generated $label/$rel"; then
        status=1
    fi
done <<<"$committed_files"

if [ "$status" -ne 0 ]; then
    echo "ERROR: committed $label differs from the generated bytes"
fi
exit "$status"
