load("//bazel/policy:defs.bzl", "policy_srcs")
load("//bazel/surface:defs.bzl", "surface_component")

policy_srcs()

exports_files(["Cargo.toml"])

surface_component(
    deps = ["//surface/contract"],
    test_deps = ["//surface/test-fixtures"],
    wasm_deps = [
        "//surface/component-support",
        "//surface/schema",
    ],
)
