load("//bazel/policy:defs.bzl", "policy_srcs")
load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

policy_srcs()

exports_files(["Cargo.toml"])

rust_binary(
    name = "brenn-usage",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
    proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = all_crate_deps(normal = True) + ["//cc-usage"],
)

rust_test(
    name = "brenn-usage_test",
    crate = ":brenn-usage",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
)
