load("//bazel/policy:defs.bzl", "policy_srcs")
load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_library", "rust_test")

policy_srcs()

exports_files(["Cargo.toml"])

rust_library(
    name = "brenn-common",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    visibility = ["//visibility:public"],
)

rust_test(
    name = "brenn-common_test",
    crate = ":brenn-common",
    edition = "2024",
)

rust_doc_test(
    name = "brenn-common_doc_test",
    crate = ":brenn-common",
)
