//! VAPID keypair file load and generate.
//!
//! On-disk format (JSON, UTF-8):
//! ```json
//! {
//!   "public_b64url": "<87-char base64url uncompressed P-256 public key>",
//!   "private_b64url": "<43-char base64url of 32-byte P-256 private scalar>"
//! }
//! ```
//!
//! The private key is stored as raw 32-byte P-256 scalar in base64url-no-pad
//! form (43 chars). The public key is stored as uncompressed X9.62 form
//! (0x04 + 32-byte X + 32-byte Y = 65 bytes → 87 chars base64url-no-pad).
//!
//! The file is written with mode 0600 on first generation. The private key
//! never leaves the server.
//!
//! Note: base64url-no-pad of 32 bytes is `ceil(32 * 4/3)` = 43 chars
//! (= 32 * 8 bits / 6 bits per char, rounded up).

use std::os::unix::fs::OpenOptionsExt as _;
use std::path::Path;
use std::sync::Arc;

use base64ct::{Base64UrlUnpadded, Encoding as _};
use p256::ecdsa::SigningKey;
use p256::ecdsa::signature::Signer as _;
use p256::elliptic_curve::sec1::ToEncodedPoint as _;
use serde::{Deserialize, Serialize};

/// Loaded VAPID keypair.
///
/// `public_b64url` is the 87-char base64url-no-pad encoding of the 65-byte
/// uncompressed P-256 public key (0x04 || X || Y). This is the
/// `applicationServerKey` value sent to the browser.
///
#[derive(Clone)]
pub struct VapidKeypair {
    /// 87-char base64url-no-pad uncompressed P-256 public key.
    /// Sent to browser as `applicationServerKey`.
    pub public_b64url: String,
    /// Parsed signing key for constructing VAPID JWT signatures per push.
    /// `Arc` for cheap clone across threads.
    pub signing_key: Arc<SigningKey>,
}

impl std::fmt::Debug for VapidKeypair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VapidKeypair")
            .field("public_b64url", &self.public_b64url)
            .field("signing_key", &"<redacted>")
            .finish()
    }
}

/// On-disk JSON representation of the keypair.
#[derive(Serialize, Deserialize)]
struct KeypairFile {
    public_b64url: String,
    private_b64url: String,
}

/// Load the VAPID keypair from `path`, generating and writing it if absent.
///
/// # Panics
///
/// - If the file exists but cannot be read (`std::io::Error`).
/// - If the file exists but cannot be JSON-parsed (corrupt keypair file is
///   an operator configuration error — panic rather than silently drop the
///   file).
/// - If the generated bytes produce an invalid key (should be impossible
///   with a correct `p256` build, but caught defensively).
/// - If the file cannot be written (permissions / filesystem error at
///   startup is a config bug, not a transient error).
pub fn load_or_generate(path: &Path) -> VapidKeypair {
    if path.exists() {
        load(path)
    } else {
        generate_and_write(path)
    }
}

fn load(path: &Path) -> VapidKeypair {
    let content = std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!(
            "config: [pwa_push].keypair_file at {} is unreadable: {e}",
            path.display()
        )
    });
    parse_keypair_file(&content, path)
}

fn parse_keypair_file(content: &str, path: &Path) -> VapidKeypair {
    let file: KeypairFile = serde_json::from_str(content).unwrap_or_else(|e| {
        panic!(
            "config: [pwa_push].keypair_file at {} is corrupt (JSON parse error): {e}",
            path.display()
        )
    });
    let private_bytes = Base64UrlUnpadded::decode_vec(&file.private_b64url).unwrap_or_else(|e| {
        panic!(
            "config: [pwa_push].keypair_file at {} has invalid private_b64url: {e}",
            path.display()
        )
    });
    // from_slice takes a 32-byte big-endian scalar.
    let secret = p256::SecretKey::from_slice(&private_bytes).unwrap_or_else(|e| {
        panic!(
            "config: [pwa_push].keypair_file at {} has unloadable private key: {e}",
            path.display()
        )
    });
    let signing_key = SigningKey::from(&secret);
    // Re-derive public key from the loaded private key to validate consistency.
    let derived_pub = derive_public_b64url(&secret);
    if derived_pub != file.public_b64url {
        panic!(
            "config: [pwa_push].keypair_file at {} — public_b64url in file does not match \
             the key derived from private_b64url (key material may be corrupt or mismatched)",
            path.display()
        );
    }
    VapidKeypair {
        public_b64url: file.public_b64url,
        signing_key: Arc::new(signing_key),
    }
}

/// Derive the base64url-no-pad uncompressed public key from a secret key.
///
/// Returns the 65-byte uncompressed point (0x04 || X || Y) encoded as
/// base64url-no-pad (87 chars). This is the exact on-disk format.
fn derive_public_b64url(secret: &p256::SecretKey) -> String {
    // to_encoded_point(false) = uncompressed (0x04 + X + Y = 65 bytes).
    let raw = secret.public_key().to_encoded_point(false);
    Base64UrlUnpadded::encode_string(raw.as_bytes())
}

fn generate_and_write(path: &Path) -> VapidKeypair {
    // OsRng is available via p256's elliptic_curve re-export.
    let mut rng = p256::elliptic_curve::rand_core::OsRng;
    let secret = p256::SecretKey::random(&mut rng);
    let private_bytes = secret.to_bytes();
    let public_b64url = derive_public_b64url(&secret);
    let private_b64url = Base64UrlUnpadded::encode_string(&private_bytes);
    let signing_key = SigningKey::from(&secret);

    let file_content = serde_json::to_string_pretty(&KeypairFile {
        public_b64url: public_b64url.clone(),
        private_b64url,
    })
    .expect("serialization of KeypairFile is infallible");

    // Atomic write: write to a temp file in the same directory, then rename.
    // This prevents a partial write from corrupting the keypair file.
    let parent = path.parent().unwrap_or(Path::new("."));
    let tmp_path = parent.join(format!(".vapid.tmp.{}", std::process::id()));

    // Write with mode 0600 (private key never world-readable).
    // `create_new(true)` (O_CREAT | O_EXCL) ensures the file is newly created,
    // so `mode(0o600)` is guaranteed to apply. A pre-existing temp file at this
    // path (e.g. from a stale prior run, or a symlink planted by an attacker)
    // is treated as an invariant violation — operator should remove it manually.
    {
        use std::io::Write as _;
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&tmp_path)
            .unwrap_or_else(|e| {
                panic!(
                    "config: failed to create VAPID keypair temp file at {} \
                     (O_CREAT|O_EXCL failed — stale temp file? remove it and restart): {e}",
                    tmp_path.display()
                )
            });
        f.write_all(file_content.as_bytes()).unwrap_or_else(|e| {
            panic!(
                "config: failed to write VAPID keypair to {}: {e}",
                tmp_path.display()
            )
        });
    }

    std::fs::rename(&tmp_path, path).unwrap_or_else(|e| {
        panic!(
            "config: failed to rename VAPID keypair from {} to {}: {e}",
            tmp_path.display(),
            path.display()
        )
    });

    tracing::info!(path = %path.display(), "generated new VAPID keypair");

    VapidKeypair {
        public_b64url,
        signing_key: Arc::new(signing_key),
    }
}

/// Build a VAPID `Authorization` header value for an RFC 8292-conformant JWT.
///
/// Implements ES256 JWT signing in-tree to avoid pulling `jwt-simple` and the
/// `rsa` chain. The JWT structure exactly matches what `web-push-native`'s
/// `with_vapid` produced:
///   - Header: `{"typ":"JWT","alg":"ES256"}`
///   - Claims: `{"aud":"<scheme>://<host>","sub":"<contact>","exp":<unix-secs>}`
///   - Signature: ES256 = ECDSA-P256 + SHA-256, fixed-length 64-byte `r||s`
///     (JOSE encoding, NOT DER/ASN.1).
/// - Returns: `format!("vapid t=<three-part-jwt>, k=<public_b64url>")`
///
/// # Correctness note
///
/// `p256::ecdsa::Signature::to_bytes()` returns the raw 64-byte `r||s` form
/// (IEEE P1363 / JOSE) — not DER. This is the encoding push services require.
/// A DER signature compiles and signs but every push service silently rejects it.
pub fn build_vapid_authorization(
    keypair: &VapidKeypair,
    endpoint: &http::Uri,
    contact: &str,
    valid_duration: std::time::Duration,
) -> String {
    let header_json = r#"{"typ":"JWT","alg":"ES256"}"#;
    let header_b64 = Base64UrlUnpadded::encode_string(header_json.as_bytes());

    // Claims: aud = scheme://host (no port, no path), sub = contact, exp = now + duration.
    // scheme and host must be present — caller guarantees a well-formed push endpoint URI
    // that has already passed validate_endpoint; absence here is an invariant violation.
    let scheme = endpoint
        .scheme_str()
        .expect("VAPID endpoint URI must have a scheme (invariant: validate_endpoint passed)");
    let host = endpoint
        .host()
        .expect("VAPID endpoint URI must have a host (invariant: validate_endpoint passed)");
    let aud = format!("{scheme}://{host}");

    let exp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("system clock is after 1970")
        .as_secs()
        + valid_duration.as_secs();

    // aud, sub, exp per RFC 8292. (iat/nbf/jti are optional and omitted.)
    // Use serde_json to build the claims object so that string values are correctly
    // JSON-escaped regardless of content — prevents silent claims corruption if the
    // operator-supplied subject or the endpoint host contains `"` or `\`.
    #[derive(serde::Serialize)]
    struct VapidClaims<'a> {
        aud: &'a str,
        sub: &'a str,
        exp: u64,
    }
    let claims_json = serde_json::to_string(&VapidClaims {
        aud: &aud,
        sub: contact,
        exp,
    })
    .expect("VapidClaims serialization is infallible");
    let claims_b64 = Base64UrlUnpadded::encode_string(claims_json.as_bytes());

    let signing_input = format!("{header_b64}.{claims_b64}");

    // ES256 sign: ECDSA-P256 + SHA-256. `.sign()` hashes internally.
    // `.to_bytes()` returns the 64-byte fixed-length r||s (JOSE form, NOT DER).
    let sig: p256::ecdsa::Signature = keypair.signing_key.sign(signing_input.as_bytes());
    let sig_b64 = Base64UrlUnpadded::encode_string(&sig.to_bytes());

    let jwt = format!("{signing_input}.{sig_b64}");

    format!("vapid t={jwt}, k={}", keypair.public_b64url)
}

#[cfg(test)]
mod tests {
    use std::os::unix::fs::PermissionsExt as _;

    use super::*;

    /// The fixed scalar-1 P-256 test key (secret + signing key). Scalar 1 is
    /// the minimum nonzero valid P-256 scalar; its public key is the generator
    /// point G. Shared so every test that pins bytes against this key builds it
    /// the same way.
    fn scalar_one_key() -> (p256::SecretKey, SigningKey) {
        let mut scalar = [0u8; 32];
        scalar[31] = 1;
        let secret =
            p256::SecretKey::from_slice(&scalar).expect("scalar 1 is a valid P-256 private key");
        let signing_key = SigningKey::from(&secret);
        (secret, signing_key)
    }

    #[test]
    fn load_or_generate_creates_file_with_mode_0600_on_first_run() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        assert!(!path.exists());

        let kp = load_or_generate(&path);
        assert!(path.exists(), "file must be created");

        let meta = std::fs::metadata(&path).expect("metadata");
        let mode = meta.permissions().mode();
        // Bottom 9 bits: owner=rw (0o600), group=none, other=none.
        assert_eq!(mode & 0o777, 0o600, "file mode must be 0600");

        // Public key: 87 chars base64url (65-byte uncompressed P-256).
        assert_eq!(kp.public_b64url.len(), 87);
    }

    #[test]
    fn load_or_generate_reads_existing_file() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");

        // Generate once.
        let kp1 = load_or_generate(&path);
        // Load again — must return the same public key.
        let kp2 = load_or_generate(&path);
        assert_eq!(kp1.public_b64url, kp2.public_b64url);
    }

    #[test]
    #[should_panic(expected = "corrupt")]
    fn corrupt_keypair_file_panics() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        std::fs::write(&path, b"not valid json").expect("write");

        let _ = load_or_generate(&path);
    }

    #[test]
    #[should_panic(expected = "public_b64url in file does not match")]
    fn mismatched_public_key_in_file_panics() {
        // Generate a valid keypair to get well-formed private_b64url.
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        load_or_generate(&path);

        // Generate a second keypair to get a *different* valid public key.
        let dir2 = tempfile::tempdir().expect("tempdir2");
        let path2 = dir2.path().join("vapid2.json");
        let kp2 = load_or_generate(&path2);

        // Read kp's private key bytes from the file it wrote.
        let content = std::fs::read_to_string(&path).expect("read kp file");
        let file_json: serde_json::Value = serde_json::from_str(&content).expect("parse kp file");
        let private_b64url = file_json["private_b64url"]
            .as_str()
            .expect("private_b64url field")
            .to_owned();

        // Write a tampered file: private from kp, public from kp2.
        let tampered = serde_json::json!({
            "public_b64url": kp2.public_b64url,
            "private_b64url": private_b64url,
        });
        let tampered_path = dir.path().join("tampered.json");
        std::fs::write(&tampered_path, tampered.to_string()).expect("write tampered file");

        let _ = load_or_generate(&tampered_path);
    }

    #[test]
    #[should_panic(expected = "invalid private_b64url")]
    fn invalid_base64_in_private_b64url_panics() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        // Valid JSON but private_b64url contains characters invalid for base64url.
        let content = r#"{"public_b64url":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","private_b64url":"not!valid"}"#;
        std::fs::write(&path, content).expect("write");
        let _ = load_or_generate(&path);
    }

    #[test]
    #[should_panic(expected = "unloadable private key")]
    fn zero_scalar_in_private_b64url_panics() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        // 32 zero bytes in base64url = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA".
        // The zero scalar is the additive identity and is rejected by p256 as an invalid key.
        // (Derive a plausible public key — it won't match, but the invalid-scalar panic fires first.)
        let content = r#"{"public_b64url":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","private_b64url":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}"#;
        std::fs::write(&path, content).expect("write");
        let _ = load_or_generate(&path);
    }

    #[test]
    fn load_or_generate_round_trips_keypair() {
        // Calling load_or_generate twice on the same path must return the same
        // public key (second call reads the file generated by the first).
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        let kp1 = load_or_generate(&path);
        let kp2 = load_or_generate(&path);
        assert_eq!(
            kp1.public_b64url, kp2.public_b64url,
            "round-trip must return same public key"
        );
    }

    #[test]
    fn public_key_is_87_chars_and_decodes_to_uncompressed_p256() {
        // base64url-no-pad of 65 bytes:
        // 65 * 8 = 520 bits / 6 = 86.67 → 87 chars.
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        let kp = load_or_generate(&path);
        // Verify the encoded value decodes to 65 bytes starting with 0x04.
        let raw = Base64UrlUnpadded::decode_vec(&kp.public_b64url).expect("decode");
        assert_eq!(
            raw.len(),
            65,
            "uncompressed P-256 public key must be 65 bytes"
        );
        assert_eq!(raw[0], 0x04, "uncompressed point must start with 0x04");
    }

    /// Test that build_vapid_authorization produces a well-formed JWT that
    /// verifies against the public key. This proves:
    /// 1. The signing input format is correct (header.claims).
    /// 2. The signature is in JOSE r||s form (not DER) — the only form push
    ///    services accept.
    /// 3. The Authorization header value has the correct `vapid t=..., k=...` shape
    ///    with `k=` matching the stored public_b64url.
    #[test]
    fn vapid_authorization_signature_verifies_against_public_key() {
        use p256::ecdsa::signature::Verifier as _;

        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("vapid.json");
        let kp = load_or_generate(&path);

        let endpoint: http::Uri = "https://fcm.googleapis.com/fcm/send/test"
            .parse()
            .expect("valid URI");
        let contact = "mailto:test@example.com";
        let valid_duration = std::time::Duration::from_secs(12 * 3600);

        let auth_header = build_vapid_authorization(&kp, &endpoint, contact, valid_duration);

        // Header must start with "vapid t=".
        assert!(
            auth_header.starts_with("vapid t="),
            "Authorization header must start with 'vapid t='; got: {auth_header}"
        );

        // Extract the JWT token (between "t=" and ", k=").
        let jwt_start = auth_header.find("t=").expect("t= present") + 2;
        let k_marker = auth_header.find(", k=").expect(", k= present");
        let jwt = &auth_header[jwt_start..k_marker];

        // Verify that k= equals the stored public_b64url.
        let k_value = &auth_header[k_marker + 4..]; // skip ", k="
        assert_eq!(
            k_value, &kp.public_b64url,
            "k= must equal stored public_b64url"
        );

        // Split JWT into three parts.
        let parts: Vec<&str> = jwt.split('.').collect();
        assert_eq!(parts.len(), 3, "JWT must have three dot-separated parts");

        let header_bytes = Base64UrlUnpadded::decode_vec(parts[0]).expect("header b64url");
        let claims_bytes = Base64UrlUnpadded::decode_vec(parts[1]).expect("claims b64url");
        let sig_bytes = Base64UrlUnpadded::decode_vec(parts[2]).expect("signature b64url");

        // Header must be {"typ":"JWT","alg":"ES256"}.
        let header_json: serde_json::Value =
            serde_json::from_slice(&header_bytes).expect("header JSON");
        assert_eq!(header_json["typ"], "JWT");
        assert_eq!(header_json["alg"], "ES256");

        // Claims must include aud (scheme://host), sub, exp.
        let claims_json: serde_json::Value =
            serde_json::from_slice(&claims_bytes).expect("claims JSON");
        assert_eq!(
            claims_json["aud"], "https://fcm.googleapis.com",
            "aud must be scheme+host only"
        );
        assert_eq!(claims_json["sub"], contact);
        assert!(claims_json["exp"].is_number(), "exp must be a number");

        // Signature must be exactly 64 bytes (r||s JOSE form, NOT DER).
        assert_eq!(
            sig_bytes.len(),
            64,
            "JOSE ES256 signature must be 64 bytes r||s; got {} bytes (DER would be ~70-72)",
            sig_bytes.len()
        );

        // Verify the signature using the verifying key derived from the keypair.
        let signing_input = format!("{}.{}", parts[0], parts[1]);
        let verifying_key = p256::ecdsa::VerifyingKey::from(kp.signing_key.as_ref());
        let sig =
            p256::ecdsa::Signature::from_slice(&sig_bytes).expect("64-byte signature must parse");
        verifying_key
            .verify(signing_input.as_bytes(), &sig)
            .expect("signature must verify against public key");
    }

    /// Known-good-vector test: fixed private key scalar, fixed inputs, verify
    /// that the JWT signature is accepted by the verifying key derived
    /// independently from the same scalar via a separate code path.
    ///
    /// This test catches systematic encoding errors (wrong claims serialization,
    /// wrong signing-input construction, wrong r||s byte order) that the
    /// random-key self-verification test cannot detect — because in that test,
    /// both sign and verify share the same in-memory keypair.
    ///
    /// Here the verifying key is re-derived from the fixed raw scalar bytes
    /// via `p256::SecretKey::from_slice → VerifyingKey::from`, completely
    /// independent of the `SigningKey` stored in `VapidKeypair`. Additionally,
    /// the signing input is reconstructed independently (by re-encoding the
    /// known header and claims) and compared byte-for-byte to what the function
    /// produced — catching any discrepancy in claim construction.
    ///
    /// Cross-library byte-equality against externally produced signatures lives
    /// in `vapid_signature_matches_external_reference_vector`; this test proves
    /// only self-consistency within p256 plus correct JWT construction.
    #[test]
    fn vapid_authorization_known_good_vector() {
        use p256::ecdsa::signature::Verifier as _;

        let (secret, signing_key) = scalar_one_key();
        let public_b64url = derive_public_b64url(&secret);

        let kp = VapidKeypair {
            public_b64url: public_b64url.clone(),
            signing_key: Arc::new(signing_key),
        };

        // Fixed inputs — deterministic so the test output is reproducible.
        let endpoint: http::Uri = "https://updates.push.services.mozilla.com/push/v1/abc"
            .parse()
            .expect("valid URI");
        let contact = "mailto:admin@example.com";
        // Fixed TTL of exactly 1 hour.
        let valid_duration = std::time::Duration::from_secs(3600);

        let auth_header = build_vapid_authorization(&kp, &endpoint, contact, valid_duration);

        // Parse the JWT from the header.
        assert!(
            auth_header.starts_with("vapid t="),
            "bad prefix: {auth_header}"
        );
        let jwt_start = auth_header.find("t=").unwrap() + 2;
        let k_marker = auth_header.find(", k=").unwrap();
        let jwt = &auth_header[jwt_start..k_marker];
        let k_value = &auth_header[k_marker + 4..];

        // k= must equal public_b64url.
        assert_eq!(k_value, &public_b64url, "k= value mismatch");

        let parts: Vec<&str> = jwt.split('.').collect();
        assert_eq!(parts.len(), 3, "JWT must have three parts");

        // Decode the three parts.
        let header_bytes = Base64UrlUnpadded::decode_vec(parts[0]).expect("header b64url");
        let claims_bytes = Base64UrlUnpadded::decode_vec(parts[1]).expect("claims b64url");
        let sig_bytes = Base64UrlUnpadded::decode_vec(parts[2]).expect("sig b64url");

        // Verify header content exactly.
        assert_eq!(
            header_bytes, br#"{"typ":"JWT","alg":"ES256"}"#,
            "header JSON mismatch"
        );

        // Verify claims content structurally (aud and sub are fully deterministic;
        // exp varies with wall clock but must be present as a number).
        let claims_json: serde_json::Value =
            serde_json::from_slice(&claims_bytes).expect("claims JSON");
        assert_eq!(
            claims_json["aud"], "https://updates.push.services.mozilla.com",
            "aud must be scheme+host only, no path"
        );
        assert_eq!(claims_json["sub"], contact, "sub mismatch");
        assert!(
            claims_json["exp"].is_u64(),
            "exp must be a non-negative integer"
        );

        // Signature must be exactly 64 bytes (JOSE r||s, not DER).
        assert_eq!(
            sig_bytes.len(),
            64,
            "signature must be 64 bytes (JOSE); got {} (DER would be 70-72)",
            sig_bytes.len()
        );

        // Re-derive the verifying key from a fresh scalar-1 SecretKey —
        // completely separate from the SigningKey stored in kp.
        let (secret2, _) = scalar_one_key();
        let verifying_key = p256::ecdsa::VerifyingKey::from(secret2.public_key());

        // Reconstruct the signing input independently from the known-good header
        // (not from `build_vapid_authorization`'s internal variable) and compare
        // byte-for-byte to what appeared in the JWT — this catches discrepancies
        // in how the function constructs the signing input.
        let expected_header_b64 =
            Base64UrlUnpadded::encode_string(br#"{"typ":"JWT","alg":"ES256"}"#);
        let expected_claims_b64 = Base64UrlUnpadded::encode_string(&claims_bytes);
        let expected_signing_input = format!("{expected_header_b64}.{expected_claims_b64}");
        let actual_signing_input = format!("{}.{}", parts[0], parts[1]);
        assert_eq!(
            actual_signing_input, expected_signing_input,
            "signing input mismatch — header or claims encoding is wrong"
        );

        // Verify the signature using the independently-derived verifying key.
        let sig =
            p256::ecdsa::Signature::from_slice(&sig_bytes).expect("64-byte signature must parse");
        verifying_key
            .verify(actual_signing_input.as_bytes(), &sig)
            .expect("signature must verify with independently-derived key");
    }

    /// Cross-library byte-equality vectors that anchor p256's deterministic
    /// ES256 sign path to the standards documents and to a second, unrelated
    /// implementation. Distinct in intent from
    /// `vapid_authorization_known_good_vector` (which proves our JWT
    /// construction is right by round-tripping through p256 itself): a failure
    /// here means p256's raw `r||s` / public-key encoding has drifted from the
    /// standard, which p256-verifies-p256 tests cannot detect because a
    /// systematic encoding bug shared by sign and verify passes symmetrically
    /// while every real push service rejects the token.
    ///
    /// Three independent anchors, all through the same `Signer::sign` path
    /// production uses (`build_vapid_authorization`), signing with the
    /// non-randomized `Signer` trait, which the `ecdsa` crate implements with
    /// RFC 6979 deterministic `k` — so a fixed scalar + fixed message yields a
    /// fixed 64-byte signature, stable across runs and machines:
    ///
    /// 1. The production-shaped VAPID signing input (`header_b64.claims_b64`,
    ///    scalar = 1), byte-equal to a signature produced by the pure-Python
    ///    `ecdsa` package — a non-RustCrypto RFC 6979 implementation.
    /// 2. The published RFC 6979 Appendix A.2.5 vector (P-256/SHA-256, message
    ///    `"sample"`), byte-equal to the `r || s` transcribed from the RFC.
    /// 3. The scalar-1 public key equals `base64url(0x04 || Gx || Gy)` for the
    ///    P-256 generator point G, with Gx/Gy transcribed from SEC 2 /
    ///    FIPS 186-4 — pinning the `k=` public-key encoding.
    ///
    /// If anchor 2 (RFC) passes but anchor 1 (python-ecdsa) fails, suspect the
    /// generation run; if both fail, suspect p256. A dependency bump that
    /// changes any of these bytes is a true positive (encoding regression),
    /// not test flakiness — RFC 6979 output must not change for fixed inputs.
    /// NEVER "fix" a failure by regenerating a vector with p256; that would
    /// reintroduce the exact circularity this test exists to break.
    ///
    /// Anchor 1 vector regeneration (pure-Python `ecdsa`, RFC 6979, raw r||s):
    /// ```python
    /// import hashlib, base64
    /// from ecdsa import SigningKey, NIST256p
    /// from ecdsa.util import sigencode_string
    /// def b(x): return base64.urlsafe_b64encode(x).rstrip(b'=').decode()
    /// h = b'{"typ":"JWT","alg":"ES256"}'
    /// c = b'{"aud":"https://updates.push.services.mozilla.com","sub":"mailto:admin@example.com","exp":1700000000}'
    /// msg = (b(h) + "." + b(c)).encode()
    /// sk = SigningKey.from_secret_exponent(1, curve=NIST256p)
    /// print(sk.sign_deterministic(msg, hashfunc=hashlib.sha256, sigencode=sigencode_string).hex())
    /// ```
    #[test]
    fn vapid_signature_matches_external_reference_vector() {
        // --- Anchor 1: production-shaped VAPID signing input, scalar = 1. ---
        // Fixed literal claims (same field order/shape as VapidClaims), `exp`
        // pinned so the signing input is fully deterministic without touching
        // the wall clock — this deliberately does NOT call
        // build_vapid_authorization (which stamps a live `exp`).
        let (secret, signing_key) = scalar_one_key();

        let header_json = br#"{"typ":"JWT","alg":"ES256"}"#;
        let claims_json = br#"{"aud":"https://updates.push.services.mozilla.com","sub":"mailto:admin@example.com","exp":1700000000}"#;
        let header_b64 = Base64UrlUnpadded::encode_string(header_json);
        let claims_b64 = Base64UrlUnpadded::encode_string(claims_json);
        let signing_input = format!("{header_b64}.{claims_b64}");

        // Signature produced by the pure-Python `ecdsa` package (RFC 6979
        // deterministic, native raw r||s) — see the regeneration script above.
        let expected_vapid_sig = hex::decode(
            "80229b6dd952d61acf12c71c3b19f1fa2f7ffbf7830ec0f908bee623521b859c\
             15eb4c04ca8b4acb0f652949c2103d5434035931c7c92fe8dbad8e14bbce6afe",
        )
        .expect("valid hex");

        let sig: p256::ecdsa::Signature = signing_key.sign(signing_input.as_bytes());
        assert_eq!(
            sig.to_bytes().as_slice(),
            expected_vapid_sig.as_slice(),
            "p256 ES256 signature over the production VAPID signing input drifted from the \
             externally generated (python-ecdsa) reference — p256 r||s encoding regression"
        );

        // --- Anchor 2: RFC 6979 Appendix A.2.5, P-256/SHA-256, msg "sample". ---
        // Private key `x`, message, and expected `r || s` transcribed verbatim
        // from the RFC text — the authoritative standards source.
        let rfc_x = hex::decode("C9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721")
            .expect("valid hex");
        let rfc_key = SigningKey::from_slice(&rfc_x).expect("RFC 6979 A.2.5 key is valid");
        let expected_rfc_sig = hex::decode(
            "EFD48B2AACB6A8FD1140DD9CD45E81D69D2C877B56AAF991C34D0EA84EAF3716\
             F7CB1C942D657C41D436C7A1B6E29F65F3E900DBB9AFF4064DC4AB2F843ACDA8",
        )
        .expect("valid hex");
        let rfc_sig: p256::ecdsa::Signature = rfc_key.sign(b"sample");
        assert_eq!(
            rfc_sig.to_bytes().as_slice(),
            expected_rfc_sig.as_slice(),
            "p256 ES256 signature disagrees with the published RFC 6979 A.2.5 r||s vector — \
             p256 deterministic-k or r||s encoding regression"
        );

        // --- Anchor 3: scalar-1 public key = base64url(0x04 || Gx || Gy). ---
        // Gx/Gy are the P-256 generator coordinates from SEC 2 / FIPS 186-4;
        // scalar 1's public key is exactly the generator point G.
        let gen_uncompressed = hex::decode(
            "04\
             6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296\
             4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5",
        )
        .expect("valid hex");
        let expected_gen_b64url = Base64UrlUnpadded::encode_string(&gen_uncompressed);
        assert_eq!(
            derive_public_b64url(&secret),
            expected_gen_b64url,
            "scalar-1 public key does not encode as base64url(0x04 || Gx || Gy) for the P-256 \
             generator — public-key (k=) encoding regression"
        );
    }
}
