load("@wasm_crates//:defs.bzl", "all_crate_deps")
load("//bazel/policy:defs.bzl", "policy_srcs")
load(
    "//bazel/wasm:defs.bzl",
    "wasm_component",
    "wasm_guest_cdylib",
)

policy_srcs()

wasm_guest_cdylib(
    name = "brenn-processor-mem-exhaust",
    shared_bindings = "//brenn-wasm:processor_bindings",
    visibility = ["//visibility:public"],
    proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = all_crate_deps(normal = True),
)

wasm_component(
    name = "component",
    module = ":brenn-processor-mem-exhaust",
    visibility = ["//visibility:public"],
)
