load("//bazel/policy:defs.bzl", "policy_srcs")
load(
    "//bazel/wasm:defs.bzl",
    "wasm_component",
    "wasm_guest_cdylib",
)

policy_srcs()

wasm_guest_cdylib(
    name = "brenn-processor-tool-test",
    shared_bindings = "//brenn-wasm:processor_bindings",
    visibility = ["//visibility:public"],
)

wasm_component(
    name = "component",
    module = ":brenn-processor-tool-test",
    visibility = ["//visibility:public"],
)
