// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type Activation = brenn::processor::types::Activation;
pub type ReceiveError = brenn::processor::types::ReceiveError;
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_receive_cabi<T_: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result12 = {
  let base11 = arg0;
  let len11 = arg1;
  let mut result11 = _rt::Vec::with_capacity(len11);
  for i in 0..len11 {
    let base = base11.add(i * (8+4*::core::mem::size_of::<*const u8>()));
    let e11 = {
      let l0 = *base.add(0).cast::<*mut u8>();
      let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      let len2 = l1;
      let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
      let l3 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base8 = l3;
      let len8 = l4;
      let mut result8 = _rt::Vec::with_capacity(len8);
      for i in 0..len8 {
        let base = base8.add(i * (2*::core::mem::size_of::<*const u8>()));
        let e8 = {
          let l5 = *base.add(0).cast::<*mut u8>();
          let l6 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len7 = l6;
          let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

          _rt::string_lift(bytes7)
        };
        result8.push(e8);
      }
      _rt::cabi_dealloc(base8, len8 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      let l9 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<i32>();
      let l10 = *base.add(4+4*::core::mem::size_of::<*const u8>()).cast::<i32>();

      brenn::processor::types::PortWindow{
        port: _rt::string_lift(bytes2),
        envelopes: result8,
        new_from: l9 as u32,
        dropped: l10 as u32,
      }
    };
    result11.push(e11);
  }
  _rt::cabi_dealloc(base11, len11 * (8+4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
  T_::receive(brenn::processor::types::Activation{
    ports: result11,
  })
};
let ptr13 = (&raw mut _RET_AREA.0).cast::<u8>();
match result12 {
  Ok(_) => { {
    *ptr13.add(0).cast::<u8>() = (0i32) as u8;
  } },
  Err(e) => { {
    *ptr13.add(0).cast::<u8>() = (1i32) as u8;
    use brenn::processor::types::ReceiveError as V16;
    match e {
      V16::MalformedEnvelope(e) => {
        *ptr13.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
        let vec14 = (e.into_bytes()).into_boxed_slice();
        let ptr14 = vec14.as_ptr().cast::<u8>();
        let len14 = vec14.len();
        ::core::mem::forget(vec14);
        *ptr13.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len14;
        *ptr13.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr14.cast_mut();
      },
      V16::ProcessingFailed(e) => {
        *ptr13.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
        let vec15 = (e.into_bytes()).into_boxed_slice();
        let ptr15 = vec15.as_ptr().cast::<u8>();
        let len15 = vec15.len();
        ::core::mem::forget(vec15);
        *ptr13.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
        *ptr13.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr15.cast_mut();
      },
    }
  } },
};ptr13
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_receive<T_: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
      match l1 {
        0 => {
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l3 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l2, l3, 1);
        },
        _ => {
          let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l5 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l4, l5, 1);
        },
      }
    },
  }
} }
pub trait Guest {
  /// Receive one activation (one or more port-windows of messages). The
  /// component processes the new portions of each port-window using earlier
  /// entries as context, and returns one result for the whole activation.
  /// Published messages (via the ports import) are buffered during execution
  /// and flushed atomically iff this returns ok; err/trap discards the buffer.
  #[allow(async_fn_in_trait)]
  fn receive(a: Activation,) -> Result<(),ReceiveError>;
}
#[doc(hidden)]

macro_rules! __export_world_processor_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "receive")]
    unsafe extern "C" fn export_receive(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_receive_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_receive")]
    unsafe extern "C" fn _post_return_receive(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_receive::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_processor_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
#[allow(dead_code, clippy::all)]
pub mod brenn {
  pub mod processor {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod ports {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[derive(Clone)]
      pub enum PublishError {
        /// Port name not bound for this component (attenuation). The guest
        /// cannot target raw channel addresses — publish is port-name-only.
        NotPermitted,
        /// Payload failed host validation (e.g. oversize). Diagnostic string.
        InvalidPayload(_rt::String),
        /// Publish budget exhausted: a per-sink token bucket, or a global
        /// per-activation backstop (message count or total bytes).
        QuotaExceeded,
      }
      impl ::core::fmt::Debug for PublishError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            PublishError::NotPermitted => {
              f.debug_tuple("PublishError::NotPermitted").finish()
            }
            PublishError::InvalidPayload(e) => {
              f.debug_tuple("PublishError::InvalidPayload").field(e).finish()
            }
            PublishError::QuotaExceeded => {
              f.debug_tuple("PublishError::QuotaExceeded").finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for PublishError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for PublishError {}
      /// Message urgency — identical to RFC 8030 §5.3 ladder. Controls whether
      /// downstream subscribers are eagerly woken or let the message park until
      /// their next natural drain. Sender expresses intent; each subscriber's
      /// `wake_min` policy decides the actual wake behavior.
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum Urgency {
        VeryLow,
        Low,
        Normal,
        High,
      }
      impl ::core::fmt::Debug for Urgency {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Urgency::VeryLow => {
              f.debug_tuple("Urgency::VeryLow").finish()
            }
            Urgency::Low => {
              f.debug_tuple("Urgency::Low").finish()
            }
            Urgency::Normal => {
              f.debug_tuple("Urgency::Normal").finish()
            }
            Urgency::High => {
              f.debug_tuple("Urgency::High").finish()
            }
          }
        }
      }

      impl Urgency{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> Urgency{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => Urgency::VeryLow,
            1 => Urgency::Low,
            2 => Urgency::Normal,
            3 => Urgency::High,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[allow(unused_unsafe, clippy::all)]
      /// Buffer one message for the bus channel bound to `port`. `payload` is
      /// the message BODY only (opaque string) — not an envelope; the host
      /// assigns all envelope fields (message id, sender, publish timestamp,
      /// channel, envelope_type, urgency). Urgency is taken from the per-port
      /// configured default (`[[wasm_consumer]] [[output]] urgency`, default
      /// `normal`). Visibility is deferred: all of an activation's publishes
      /// flush atomically, in call order, iff receive returns ok; err/trap
      /// discards them all.
      ///
      /// **Provenance / trust note:** Messages emitted via this import appear on
      /// the bus with `sender = "wasm:<slug>"` and `envelope_type = brenn`.
      /// External-origin content forwarded through a component (e.g. a webhook body
      /// republished as a brenn envelope) retains no marker of its external origin.
      /// Downstream subscribers that make trust decisions based on `envelope_type` or
      /// `sender` will treat forwarded external content as internally-originated.
      /// Operators MUST NOT bind a component's output port to a channel whose
      /// subscribers assume internal-only senders, unless the component is known to
      /// publish only internal-origin content. The sender of a republished message
      /// is the component that published it; trust derives from the operator-authored
      /// wiring and the ACLs it was granted, not from any per-message origin marker.
      #[allow(async_fn_in_trait)]
      pub fn publish(port: &str,payload: &str,) -> Result<(),PublishError>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
          let vec0 = port;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = payload;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/ports@0.1.0")]
          unsafe extern "C" {
            #[link_name = "publish"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result10 = match l4 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l5 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v9 = match l5 {
                  0 => {
                    PublishError::NotPermitted
                  }
                  1 => {
                    let e9 = {
                      let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l7 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len8 = l7;
                      let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                      _rt::string_lift(bytes8)
                    };
                    PublishError::InvalidPayload(e9)
                  }
                  n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    PublishError::QuotaExceeded
                  }
                };

                v9
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result10
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// Like `publish`, but with an explicit urgency override. Use when the
      /// guest has message-specific urgency intent that differs from the port
      /// default. Existing components compiled without this import keep working
      /// (additive WIT ABI — no package version bump).
      #[allow(async_fn_in_trait)]
      pub fn publish_with_urgency(port: &str,payload: &str,urgency: Urgency,) -> Result<(),PublishError>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
          let vec0 = port;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = payload;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/ports@0.1.0")]
          unsafe extern "C" {
            #[link_name = "publish-with-urgency"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, ) { unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, urgency.clone() as i32, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result10 = match l4 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l5 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v9 = match l5 {
                  0 => {
                    PublishError::NotPermitted
                  }
                  1 => {
                    let e9 = {
                      let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l7 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len8 = l7;
                      let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                      _rt::string_lift(bytes8)
                    };
                    PublishError::InvalidPayload(e9)
                  }
                  n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    PublishError::QuotaExceeded
                  }
                };

                v9
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result10
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod store {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// Opaque handle to an in-flight transaction. The host owns the resource;
      /// the component receives an index and must commit or rollback before the
      /// instance returns from its export call. A handle dropped without
      /// commit/rollback is a contract violation — the host's HostTransaction::drop
      /// detects the still-active tx via the tx_active flag, attempts a cleanup
      /// rollback, then returns Err(...) (wasmtime treats a destructor-returned Err
      /// as a runtime trap). The trap surfaces to the host as Err(wasmtime::Error)
      /// on the owning receive call, which ProcessorComponent::handle then surfaces
      /// as a contained Trap (not a panic).

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Transaction{
        handle: _rt::Resource<Transaction>,
      }

      impl Transaction{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Transaction{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]transaction"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      /// All store failures the component can observe.
      #[derive(Clone)]
      pub enum StoreError {
        /// Another writer holds the lock and the host's wait budget was
        /// exhausted. Transient. Reserved; not produced in this slice (the
        /// process-global path guard precludes cross-instance contention).
        Contention,
        /// Storage subsystem failure or contract violation. String is
        /// host-side diagnostic, opaque to the component. Covers nested
        /// begin, SQLite errors, file corruption.
        Backend(_rt::String),
        /// Host-enforced per-store size cap reached. The write was rejected
        /// atomically; no partial state committed. Distinct from backend(...)
        /// (disk-full / corruption): this is the host's own quota, recoverable
        /// by the guest's prune/delete path.
        QuotaExceeded,
      }
      impl ::core::fmt::Debug for StoreError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            StoreError::Contention => {
              f.debug_tuple("StoreError::Contention").finish()
            }
            StoreError::Backend(e) => {
              f.debug_tuple("StoreError::Backend").field(e).finish()
            }
            StoreError::QuotaExceeded => {
              f.debug_tuple("StoreError::QuotaExceeded").finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for StoreError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for StoreError {}
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Read a value for (namespace, key) within this transaction. Returns
        /// none if the key is absent. Errors are storage-layer failures.
        #[allow(async_fn_in_trait)]
        pub fn get(&self,namespace: &str,key: &[u8],) -> Result<Option<_rt::Vec::<u8>>,StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = key;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.get"]
              fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import3((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
            let l4 = i32::from(*ptr2.add(0).cast::<u8>());
            let result14 = match l4 {
              0 => {
                let e = {
                  let l5 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                  match l5 {
                    0 => None,
                    1 => {
                      let e = {
                        let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l7 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len8 = l7;

                        <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l6.cast(), len8, len8))
                      };
                      Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                  }
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l9 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v13 = match l9 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e13 = {
                        let l10 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l11 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len12 = l11;
                        let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                        _rt::string_lift(bytes12)
                      };
                      StoreError::Backend(e13)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v13
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result14
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Write or replace a value. Idempotent w.r.t. value equality.
        #[allow(async_fn_in_trait)]
        pub fn put(&self,namespace: &str,key: &[u8],value: &[u8],) -> Result<(),StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = key;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let vec2 = value;
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.put"]
              fn wit_import4(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import4(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import4((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3);
            let l5 = i32::from(*ptr3.add(0).cast::<u8>());
            let result11 = match l5 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l6 = i32::from(*ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v10 = match l6 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e10 = {
                        let l7 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l8 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len9 = l8;
                        let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                        _rt::string_lift(bytes9)
                      };
                      StoreError::Backend(e10)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v10
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result11
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Delete a key. Absent key is a no-op (not an error).
        #[allow(async_fn_in_trait)]
        pub fn delete(&self,namespace: &str,key: &[u8],) -> Result<(),StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = key;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.delete"]
              fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import3((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
            let l4 = i32::from(*ptr2.add(0).cast::<u8>());
            let result10 = match l4 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l5 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v9 = match l5 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e9 = {
                        let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l7 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len8 = l7;
                        let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                        _rt::string_lift(bytes8)
                      };
                      StoreError::Backend(e9)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v9
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result10
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// List keys in namespace in ascending key order, between start (inclusive)
        /// and end (exclusive). end = none means to-the-end. limit = 0 means
        /// unlimited. Returns (key, value) pairs.
        #[allow(async_fn_in_trait)]
        pub fn scan(&self,namespace: &str,start: &[u8],end: Option<&[u8]>,limit: u32,) -> Result<_rt::Vec::<(_rt::Vec::<u8>,_rt::Vec::<u8>,)>,StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = start;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let (result3_0,result3_1,result3_2,) = match end {
              Some(e) => {
                let vec2 = e;
                let ptr2 = vec2.as_ptr().cast::<u8>();
                let len2 = vec2.len();

                (1i32, ptr2.cast_mut(), len2)
              },
              None => {
                (0i32, ::core::ptr::null_mut(), 0usize)
              },
            };let ptr4 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.scan"]
              fn wit_import5(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import5(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, ) { unreachable!() }
            wit_import5((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, result3_0, result3_1, result3_2, _rt::as_i32(&limit), ptr4);
            let l6 = i32::from(*ptr4.add(0).cast::<u8>());
            let result21 = match l6 {
              0 => {
                let e = {
                  let l7 = *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l8 = *ptr4.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base15 = l7;
                  let len15 = l8;
                  let mut result15 = _rt::Vec::with_capacity(len15);
                  for i in 0..len15 {
                    let base = base15.add(i * (4*::core::mem::size_of::<*const u8>()));
                    let e15 = {
                      let l9 = *base.add(0).cast::<*mut u8>();
                      let l10 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len11 = l10;
                      let l12 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l13 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len14 = l13;

                      (<_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l9.cast(), len11, len11)), <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l12.cast(), len14, len14)))
                    };
                    result15.push(e15);
                  }
                  _rt::cabi_dealloc(base15, len15 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());

                  result15
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l16 = i32::from(*ptr4.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v20 = match l16 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e20 = {
                        let l17 = *ptr4.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l18 = *ptr4.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len19 = l18;
                        let bytes19 = _rt::Vec::from_raw_parts(l17.cast(), len19, len19);

                        _rt::string_lift(bytes19)
                      };
                      StoreError::Backend(e20)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v20
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result21
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Commit the transaction. The handle is consumed (resource dropped).
        /// On COMMIT failure, host attempts ROLLBACK; if that also fails, the
        /// host panics (fail-fast). The component sees only store-error on the
        /// structured failure path.
        #[allow(async_fn_in_trait)]
        pub fn commit(&self,) -> Result<(),StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.commit"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result8 = match l2 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v7 = match l3 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e7 = {
                        let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l5 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                        _rt::string_lift(bytes6)
                      };
                      StoreError::Backend(e7)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v7
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result8
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Abort the transaction. The handle is consumed.
        #[allow(async_fn_in_trait)]
        pub fn rollback(&self,) -> (){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.rollback"]
              fn wit_import0(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) { unreachable!() }
            wit_import0((self).handle() as i32);
          }
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// Start a new transaction. SQLite BEGIN IMMEDIATE under the hood:
      /// acquires the write lock now. A second begin from the same component
      /// instance before commit/rollback returns backend("nested transaction
      /// not supported"). The contention variant is reserved for later slices.
      #[allow(async_fn_in_trait)]
      pub fn begin() -> Result<Transaction,StoreError>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/store@0.1.0")]
          unsafe extern "C" {
            #[link_name = "begin"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result9 = match l2 {
            0 => {
              let e = {
                let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<i32>();

                Transaction::from_handle(l3 as u32)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l4 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v8 = match l4 {
                  0 => {
                    StoreError::Contention
                  }
                  1 => {
                    let e8 = {
                      let l5 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l6 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len7 = l6;
                      let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                      _rt::string_lift(bytes7)
                    };
                    StoreError::Backend(e8)
                  }
                  n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    StoreError::QuotaExceeded
                  }
                };

                v8
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result9
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod log {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      /// Maps 1:1 onto the host's tracing levels.
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum Level {
        Trace,
        Debug,
        Info,
        Warn,
        Error,
      }
      impl ::core::fmt::Debug for Level {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Level::Trace => {
              f.debug_tuple("Level::Trace").finish()
            }
            Level::Debug => {
              f.debug_tuple("Level::Debug").finish()
            }
            Level::Info => {
              f.debug_tuple("Level::Info").finish()
            }
            Level::Warn => {
              f.debug_tuple("Level::Warn").finish()
            }
            Level::Error => {
              f.debug_tuple("Level::Error").finish()
            }
          }
        }
      }

      impl Level{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> Level{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => Level::Trace,
            1 => Level::Debug,
            2 => Level::Info,
            3 => Level::Warn,
            4 => Level::Error,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[allow(unused_unsafe, clippy::all)]
      /// Emit one diagnostic log line through the host's log pipeline.
      ///
      /// Fire-and-forget, best-effort, IMMEDIATE: unlike `ports.publish`, log
      /// emission is NOT buffered and NOT transactional with the activation
      /// outcome — lines emitted before a later trap/err are kept (that is the
      /// point: diagnostics must survive failure). The host attributes every
      /// line to the emitting component; the guest cannot spoof attribution.
      /// The message is truncated (UTF-8-safe) and control-escaped by the host.
      /// Calls beyond the per-activation quota are dropped (host logs the
      /// suppressed count once after the activation).
      #[allow(async_fn_in_trait)]
      pub fn log(level: Level,message: &str,) -> (){
        unsafe {
          let vec0 = message;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/log@0.1.0")]
          unsafe extern "C" {
            #[link_name = "log"]
            fn wit_import1(_: i32, _: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(level.clone() as i32, ptr0.cast_mut(), len0);
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod alert {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      /// Maps 1:1 onto the host's alert severities.
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum Severity {
        Info,
        Warning,
        Critical,
      }
      impl ::core::fmt::Debug for Severity {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Severity::Info => {
              f.debug_tuple("Severity::Info").finish()
            }
            Severity::Warning => {
              f.debug_tuple("Severity::Warning").finish()
            }
            Severity::Critical => {
              f.debug_tuple("Severity::Critical").finish()
            }
          }
        }
      }

      impl Severity{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> Severity{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => Severity::Info,
            1 => Severity::Warning,
            2 => Severity::Critical,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[allow(unused_unsafe, clippy::all)]
      /// Page the operator through the host's alerting pipeline (e.g. mail).
      ///
      /// Fire-and-forget, best-effort: delivery is subject to the host's
      /// process-wide alert rate limiter and queue; an accepted call is not an
      /// acknowledgment of delivery (which is why there is no result type —
      /// `ok` would lie). Title and body are truncated and control-escaped;
      /// the host prefixes the title with the component identity. Calls beyond
      /// the per-activation quota are dropped (host logs the suppressed count).
      /// Use for conditions a human should act on; use `log.log` for everything
      /// else. There is NO implicit log-level→alert escalation: `log.log(error,
      /// …)` never alerts.
      #[allow(async_fn_in_trait)]
      pub fn alert(severity: Severity,title: &str,body: &str,) -> (){
        unsafe {
          let vec0 = title;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = body;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/alert@0.1.0")]
          unsafe extern "C" {
            #[link_name = "alert"]
            fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, ) { unreachable!() }
          wit_import2(severity.clone() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1);
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod config {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      /// Read one operator-supplied config value. Values are opaque strings;
      /// the guest parses. The map is fixed for the process lifetime (seeded
      /// from host TOML at startup; changes require a host restart). Keys
      /// under the reserved prefix "brenn." are host-injected facts (e.g.
      /// "brenn.max-skew-secs" on replay components bound to a timestamped
      /// signature scheme); operator TOML cannot set them.
      #[allow(async_fn_in_trait)]
      pub fn get(key: &str,) -> Option<_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = key;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/config@0.1.0")]
          unsafe extern "C" {
            #[link_name = "get"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result7 = match l3 {
            0 => None,
            1 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;
                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                _rt::string_lift(bytes6)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result7
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod mqtt {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// Failure modes the guest can observe from a synchronous MQTT publish.
      /// Distinct variants so a guest can tell a transient broker outage
      /// (`broker`) from a permanent denial (`not-permitted`): the former MAY be
      /// retried on a later activation, the latter never.
      #[derive(Clone)]
      pub enum MqttPublishError {
        /// Grant/ACL denied for the target client — the consumer's
        /// `mqtt_publish` ACL does not list this client (or the `mqtt` grant is
        /// absent). Permanent for this config; do not retry.
        NotPermitted,
        /// The MQTT service is not configured on this server (no `[[mqtt_client]]`
        /// is declared, so no session exists to publish through). Permanent for
        /// this config; do not retry. (Kept as a stable WIT variant; its reachable
        /// meaning narrowed to the service-absent case — a validly-booted server
        /// with a declared client always has a session, since every ACL-authorized
        /// client is validated and registered at boot.)
        NoConnector,
        /// Address parse / wildcard / oversize failure. Diagnostic string.
        InvalidPayload(_rt::String),
        /// Per-activation publish quota hit (shared with `ports.publish`).
        QuotaExceeded,
        /// Broker disconnect / submit failure / ack drop. Transient — MAY be
        /// retried on a later activation. The payload is a stable coarse kind
        /// (e.g. `"not connected"` / `"publish failed"`) suitable for logging
        /// and retry classification; it is NOT the full host-side error detail
        /// and MUST NOT be parsed beyond that classification.
        Broker(_rt::String),
        /// Broker accepted the connection but rejected the publish (PUBACK
        /// reason code != success). Diagnostic string.
        BrokerRejected(_rt::String),
      }
      impl ::core::fmt::Debug for MqttPublishError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            MqttPublishError::NotPermitted => {
              f.debug_tuple("MqttPublishError::NotPermitted").finish()
            }
            MqttPublishError::NoConnector => {
              f.debug_tuple("MqttPublishError::NoConnector").finish()
            }
            MqttPublishError::InvalidPayload(e) => {
              f.debug_tuple("MqttPublishError::InvalidPayload").field(e).finish()
            }
            MqttPublishError::QuotaExceeded => {
              f.debug_tuple("MqttPublishError::QuotaExceeded").finish()
            }
            MqttPublishError::Broker(e) => {
              f.debug_tuple("MqttPublishError::Broker").field(e).finish()
            }
            MqttPublishError::BrokerRejected(e) => {
              f.debug_tuple("MqttPublishError::BrokerRejected").field(e).finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for MqttPublishError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for MqttPublishError {}
      #[allow(unused_unsafe, clippy::all)]
      /// Publish synchronously to an MQTT broker. Unlike `ports.publish`
      /// (buffered, flushed atomically at activation end), this goes STRAIGHT to
      /// the broker and returns the broker outcome inline — there is no
      /// store-and-forward, no queuing, no retry.
      ///
      /// **Not transactional with the activation outcome.** Because the send is
      /// immediate, a message published here has ALREADY reached the broker by the
      /// time a later trap or err aborts the activation; it is NOT rolled back.
      /// This is a genuine semantic difference from `ports.publish`, which
      /// discards its whole buffer on failure. A guest needing all-or-nothing
      /// semantics across MQTT + bus must NOT mix the two — the MQTT side effect
      /// is not retractable. (Same immediacy as `log` / `alert`.)
      ///
      /// `client` is the `[[mqtt_client]]` slug (mirrors the LLM `MqttSend`
      /// tool's `<client>` address segment); `topic` is the topic under that
      /// client and MUST NOT contain wildcards. The consumer's `mqtt_publish` ACL
      /// gates which clients are reachable. For QoS >= 1 the call awaits the
      /// PUBACK before returning.
      #[allow(async_fn_in_trait)]
      pub fn mqtt_publish(client: &str,topic: &str,payload: &[u8],content_type: Option<&str>,qos: u8,retain: bool,) -> Result<(),MqttPublishError>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
          let vec0 = client;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = topic;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let vec2 = payload;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          let (result4_0,result4_1,result4_2,) = match content_type {
            Some(e) => {
              let vec3 = e;
              let ptr3 = vec3.as_ptr().cast::<u8>();
              let len3 = vec3.len();

              (1i32, ptr3.cast_mut(), len3)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let ptr5 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/mqtt@0.1.0")]
          unsafe extern "C" {
            #[link_name = "mqtt-publish"]
            fn wit_import6(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import6(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, ) { unreachable!() }
          wit_import6(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, result4_0, result4_1, result4_2, _rt::as_i32(&qos), match &retain { true => 1, false => 0 }, ptr5);
          let l7 = i32::from(*ptr5.add(0).cast::<u8>());
          let result19 = match l7 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l8 = i32::from(*ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v18 = match l8 {
                  0 => {
                    MqttPublishError::NotPermitted
                  }
                  1 => {
                    MqttPublishError::NoConnector
                  }
                  2 => {
                    let e18 = {
                      let l9 = *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l10 = *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len11 = l10;
                      let bytes11 = _rt::Vec::from_raw_parts(l9.cast(), len11, len11);

                      _rt::string_lift(bytes11)
                    };
                    MqttPublishError::InvalidPayload(e18)
                  }
                  3 => {
                    MqttPublishError::QuotaExceeded
                  }
                  4 => {
                    let e18 = {
                      let l12 = *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l13 = *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len14 = l13;
                      let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);

                      _rt::string_lift(bytes14)
                    };
                    MqttPublishError::Broker(e18)
                  }
                  n => {
                    debug_assert_eq!(n, 5, "invalid enum discriminant");
                    let e18 = {
                      let l15 = *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l16 = *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len17 = l16;
                      let bytes17 = _rt::Vec::from_raw_parts(l15.cast(), len17, len17);

                      _rt::string_lift(bytes17)
                    };
                    MqttPublishError::BrokerRejected(e18)
                  }
                };

                v18
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result19
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod tools {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// Failure modes a guest can observe from a tool call. Mirrors the host-side
      /// `ToolError` (the native registry's error type); the fast and async classes
      /// share this variant because from the caller's viewpoint a tool is one object
      /// regardless of class.
      #[derive(Clone)]
      pub enum ToolError {
        /// Unknown tool OR a tool this component was not granted — deliberately
        /// indistinguishable, so a probing guest learns nothing about what exists
        /// (the same oracle-closure as an out-of-visibility reply target).
        NotGranted,
        /// ACL clause miss: the args named a resource outside this component's
        /// grant. Diagnostic string names the offending resource (the caller
        /// already named it, so it is not an information leak).
        Denied(_rt::String),
        /// Args JSON was malformed, oversize, or failed the tool's own arg
        /// deserialization. Diagnostic string.
        InvalidArgs(_rt::String),
        /// The caller's per-(participant, tool) rate bucket was empty. Fast tools
        /// fail immediately with this; async tools delay rather than return it.
        RateLimited,
        /// `call-fast` on an async tool, or `call-async` on a fast tool. The class
        /// is the tool's, never the caller's.
        WrongClass,
        /// A tool bug the host has already alerted on (e.g. an oversize result, an
        /// internal execution fault, or a per-activation call-count overflow). The
        /// string is a stable coarse token, not host-side detail.
        Internal(_rt::String),
      }
      impl ::core::fmt::Debug for ToolError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            ToolError::NotGranted => {
              f.debug_tuple("ToolError::NotGranted").finish()
            }
            ToolError::Denied(e) => {
              f.debug_tuple("ToolError::Denied").field(e).finish()
            }
            ToolError::InvalidArgs(e) => {
              f.debug_tuple("ToolError::InvalidArgs").field(e).finish()
            }
            ToolError::RateLimited => {
              f.debug_tuple("ToolError::RateLimited").finish()
            }
            ToolError::WrongClass => {
              f.debug_tuple("ToolError::WrongClass").finish()
            }
            ToolError::Internal(e) => {
              f.debug_tuple("ToolError::Internal").field(e).finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for ToolError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for ToolError {}
      #[allow(unused_unsafe, clippy::all)]
      /// Invoke a fast-class tool synchronously and return its JSON result.
      ///
      /// Fast tools are bounded, non-blocking host operations (in-memory lookups,
      /// cheap local reads). The host enforces a per-tool time budget; overrun is a
      /// *tool bug* that the host alerts on, not a guest fault. `args-json` is the
      /// tool's argument object serialized as JSON (UTF-8), capped by the host; the
      /// returned string is the tool's result JSON, also capped. Grant + ACL are
      /// checked against `args-json` at call time. Calling a fast tool that is
      /// actually async yields `wrong-class`.
      #[allow(async_fn_in_trait)]
      pub fn call_fast(tool: &str,args_json: &str,) -> Result<_rt::String,ToolError>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
          let vec0 = tool;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = args_json;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/tools@0.1.0")]
          unsafe extern "C" {
            #[link_name = "call-fast"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result19 = match l4 {
            0 => {
              let e = {
                let l5 = *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len7 = l6;
                let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                _rt::string_lift(bytes7)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l8 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v18 = match l8 {
                  0 => {
                    ToolError::NotGranted
                  }
                  1 => {
                    let e18 = {
                      let l9 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l10 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len11 = l10;
                      let bytes11 = _rt::Vec::from_raw_parts(l9.cast(), len11, len11);

                      _rt::string_lift(bytes11)
                    };
                    ToolError::Denied(e18)
                  }
                  2 => {
                    let e18 = {
                      let l12 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l13 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len14 = l13;
                      let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);

                      _rt::string_lift(bytes14)
                    };
                    ToolError::InvalidArgs(e18)
                  }
                  3 => {
                    ToolError::RateLimited
                  }
                  4 => {
                    ToolError::WrongClass
                  }
                  n => {
                    debug_assert_eq!(n, 5, "invalid enum discriminant");
                    let e18 = {
                      let l15 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l16 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len17 = l16;
                      let bytes17 = _rt::Vec::from_raw_parts(l15.cast(), len17, len17);

                      _rt::string_lift(bytes17)
                    };
                    ToolError::Internal(e18)
                  }
                };

                v18
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result19
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// Enqueue an async-class tool call. Returns as soon as the request is
      /// validated and buffered — the *result* arrives later as a separate bus
      /// activation on this component's tool-result inbox, correlated by `call-id`.
      ///
      /// Grant + ACL + arg-size are checked synchronously here (so caller mistakes
      /// fail fast with a typed error); on success the request rides the activation's
      /// transactional flush — it reaches the bus iff this activation returns ok, so
      /// a trapped activation fires no tool calls. `call-id` is a caller-chosen
      /// opaque correlation string (echoed verbatim in the result); the caller owns
      /// its uniqueness and keeps in-flight state in its `store` grant keyed by it.
      #[allow(async_fn_in_trait)]
      pub fn call_async(tool: &str,args_json: &str,call_id: &str,) -> Result<(),ToolError>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
          let vec0 = tool;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = args_json;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let vec2 = call_id;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:processor/tools@0.1.0")]
          unsafe extern "C" {
            #[link_name = "call-async"]
            fn wit_import4(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import4(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import4(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3);
          let l5 = i32::from(*ptr3.add(0).cast::<u8>());
          let result17 = match l5 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l6 = i32::from(*ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v16 = match l6 {
                  0 => {
                    ToolError::NotGranted
                  }
                  1 => {
                    let e16 = {
                      let l7 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l8 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len9 = l8;
                      let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                      _rt::string_lift(bytes9)
                    };
                    ToolError::Denied(e16)
                  }
                  2 => {
                    let e16 = {
                      let l10 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l11 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len12 = l11;
                      let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                      _rt::string_lift(bytes12)
                    };
                    ToolError::InvalidArgs(e16)
                  }
                  3 => {
                    ToolError::RateLimited
                  }
                  4 => {
                    ToolError::WrongClass
                  }
                  n => {
                    debug_assert_eq!(n, 5, "invalid enum discriminant");
                    let e16 = {
                      let l13 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l14 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len15 = l14;
                      let bytes15 = _rt::Vec::from_raw_parts(l13.cast(), len15, len15);

                      _rt::string_lift(bytes15)
                    };
                    ToolError::Internal(e16)
                  }
                };

                v16
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result17
        }
      }

    }

    /// External ABI — out-of-tree components are first-class consumers of this
    /// interface. Evolution is additive-import-only (decisions.md §2 caveats).
    ///
    /// The invariant this interface serves:
    ///
    ///   There is one component model. Any component runs on any host that can
    ///   satisfy its imports. Hosting eligibility is an import profile, not a
    ///   component kind.
    ///
    /// A component importing `store`/`mqtt`/`tools` is backend-only; one importing
    /// DOM capability is surface-only. Same rule, different import profile — not
    /// two kinds of thing. Components see exactly one mechanism: messages on named
    /// ports.
    ///
    /// Host linking policy: each interface in `world processor` is linked
    /// per-component only when the operator grants it (`grants` field in
    /// `[[wasm_consumer]]`). Components should import only the interfaces they
    /// actually use (import-GC removes unused imports from built artifacts);
    /// importing an ungranted interface causes a named load-time panic. Version
    /// matching follows wasmtime's semver-compatibility rule: same major.minor for
    /// 0.x, same major for >=1.0.0.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// One message in the window: the canonical MessageEnvelope serialized as
      /// JSON (UTF-8). The host does not parse `body` and does not pre-classify
      /// `envelope_type`; the guest parses it and fails deserialization if it
      /// does not understand the envelope.
      ///
      /// Envelope-type additivity policy: `envelope_type` is an OPEN string set.
      /// New values (e.g. `"ephemeral"`) are added additively and appear on the
      /// wire only together with the feature that can deliver them to guests —
      /// a guest never observes a value for a delivery class it cannot receive.
      /// Guests fail deserialization on an unrecognized envelope (the posture
      /// stated above), so an additive new value is safe for out-of-tree
      /// consumers by construction.
      pub type EnvelopeJson = _rt::String;
      /// Messages delivered on one logical input port for this activation.
      #[derive(Clone)]
      pub struct PortWindow {
        /// Logical input port name from host config — never a raw channel address.
        pub port: _rt::String,
        /// Ordered list, oldest→newest, of MessageEnvelope JSON values for the
        /// delivering channel. Entries before `new-from` are RETAINED CONTEXT:
        /// the most-recent up-to-`retain_depth` channel messages preceding the
        /// new set. These are channel-wide most-recent messages, NOT a
        /// per-subscriber delivered log — on a component's first window after
        /// (re)subscription the context MAY include channel messages this
        /// component was never individually delivered. Treat `new-from` as "the
        /// most-recent prior channel messages are provided as context here," NOT
        /// as "I have already processed everything before this index." A guest
        /// needing exactly-once-seen semantics must track its own high-water by
        /// `message_id`. Entries from `new-from` onward are this invocation's
        /// new/unprocessed messages (up to `push_depth`).
        ///
        /// ATTACH IS A DELIVERY POINT. When a port's queue comes into existence
        /// — the instance's first attach, a re-attach, or a binding added or
        /// rebound by a config change — the channel's retained tail, capped at
        /// `push_depth`, is delivered as NEW, not as context, and it wakes the
        /// component. A message published while the channel had no consumer
        /// therefore still reaches the consumer that attaches afterwards, so a
        /// guest MAY rely on the new set alone to catch up on attach. The
        /// corollary: a re-attach re-delivers as new what the guest already
        /// processed, so a guest whose handling is side-effecting MUST make it
        /// at-most-once by `message_id`.
        pub envelopes: _rt::Vec::<EnvelopeJson>,
        /// Index into `envelopes` of the first new/unprocessed message. Equals
        /// `envelopes` length when the window is pure context with no new messages.
        /// This is normal for sampled ports (`push_depth = 0`) and for triggering
        /// ports that had no pending rows in this activation step.
        pub new_from: u32,
        /// Count of messages lost to push-overflow (`push_depth` exceeded:
        /// rolled past the push window before the component consumed them)
        /// since the previous successful invocation, so the guest can detect
        /// gaps. BEST-EFFORT / SINCE-BOOT: the underlying counter is volatile
        /// (in host memory only) and resets to 0 across a host restart, so a
        /// gap that occurred before a crash is NOT reflected here after the
        /// restart. `dropped == 0` is therefore not proof of no-gap across a
        /// host lifetime; treat it as a within-lifetime gap signal only.
        /// Always 0 for sampled ports (`push_depth = 0`), which never have
        /// push rows and therefore never experience push-overflow.
        pub dropped: u32,
      }
      impl ::core::fmt::Debug for PortWindow {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("PortWindow").field("port", &self.port).field("envelopes", &self.envelopes).field("new-from", &self.new_from).field("dropped", &self.dropped).finish()
        }
      }
      /// One activation. Contains one `port-window` per bound input port, in
      /// the order declared in the consumer's config (`cfg.inputs` order). Every
      /// bound port appears in every activation; a port with no new messages
      /// arrives as a pure-context window (`new-from == envelopes` length).
      /// Guests must not assume `ports` has length 1.
      #[derive(Clone)]
      pub struct Activation {
        pub ports: _rt::Vec::<PortWindow>,
      }
      impl ::core::fmt::Debug for Activation {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Activation").field("ports", &self.ports).finish()
        }
      }
      /// Outcome of processing the batch. A guest trap is a distinct,
      /// host-observed failure (not representable here).
      #[derive(Clone)]
      pub enum ReceiveError {
        /// Guest could not parse one of the envelope JSON values it was handed.
        MalformedEnvelope(_rt::String),
        /// Guest-defined processing failure with a diagnostic message.
        ProcessingFailed(_rt::String),
      }
      impl ::core::fmt::Debug for ReceiveError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            ReceiveError::MalformedEnvelope(e) => {
              f.debug_tuple("ReceiveError::MalformedEnvelope").field(e).finish()
            }
            ReceiveError::ProcessingFailed(e) => {
              f.debug_tuple("ReceiveError::ProcessingFailed").field(e).finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for ReceiveError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for ReceiveError {}

    }

  }
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  

  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen_rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_processor_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_processor_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_processor_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.58.0:brenn:processor@0.1.0:processor:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1956] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa4\x0e\x01A\x02\x01\
A\x17\x01B\x09\x01q\x03\x0dnot-permitted\0\0\x0finvalid-payload\x01s\0\x0equota-\
exceeded\0\0\x04\0\x0dpublish-error\x03\0\0\x01m\x04\x08very-low\x03low\x06norma\
l\x04high\x04\0\x07urgency\x03\0\x02\x01j\0\x01\x01\x01@\x02\x04ports\x07payload\
s\0\x04\x04\0\x07publish\x01\x05\x01@\x03\x04ports\x07payloads\x07urgency\x03\0\x04\
\x04\0\x14publish-with-urgency\x01\x06\x03\0\x1bbrenn:processor/ports@0.1.0\x05\0\
\x01B\x1b\x04\0\x0btransaction\x03\x01\x01q\x03\x0acontention\0\0\x07backend\x01\
s\0\x0equota-exceeded\0\0\x04\0\x0bstore-error\x03\0\x01\x01h\0\x01p}\x01k\x04\x01\
j\x01\x05\x01\x02\x01@\x03\x04self\x03\x09namespaces\x03key\x04\0\x06\x04\0\x17[\
method]transaction.get\x01\x07\x01j\0\x01\x02\x01@\x04\x04self\x03\x09namespaces\
\x03key\x04\x05value\x04\0\x08\x04\0\x17[method]transaction.put\x01\x09\x01@\x03\
\x04self\x03\x09namespaces\x03key\x04\0\x08\x04\0\x1a[method]transaction.delete\x01\
\x0a\x01o\x02\x04\x04\x01p\x0b\x01j\x01\x0c\x01\x02\x01@\x05\x04self\x03\x09name\
spaces\x05start\x04\x03end\x05\x05limity\0\x0d\x04\0\x18[method]transaction.scan\
\x01\x0e\x01@\x01\x04self\x03\0\x08\x04\0\x1a[method]transaction.commit\x01\x0f\x01\
@\x01\x04self\x03\x01\0\x04\0\x1c[method]transaction.rollback\x01\x10\x01i\0\x01\
j\x01\x11\x01\x02\x01@\0\0\x12\x04\0\x05begin\x01\x13\x03\0\x1bbrenn:processor/s\
tore@0.1.0\x05\x01\x01B\x04\x01m\x05\x05trace\x05debug\x04info\x04warn\x05error\x04\
\0\x05level\x03\0\0\x01@\x02\x05level\x01\x07messages\x01\0\x04\0\x03log\x01\x02\
\x03\0\x19brenn:processor/log@0.1.0\x05\x02\x01B\x04\x01m\x03\x04info\x07warning\
\x08critical\x04\0\x08severity\x03\0\0\x01@\x03\x08severity\x01\x05titles\x04bod\
ys\x01\0\x04\0\x05alert\x01\x02\x03\0\x1bbrenn:processor/alert@0.1.0\x05\x03\x01\
B\x03\x01ks\x01@\x01\x03keys\0\0\x04\0\x03get\x01\x01\x03\0\x1cbrenn:processor/c\
onfig@0.1.0\x05\x04\x01B\x07\x01q\x06\x0dnot-permitted\0\0\x0cno-connector\0\0\x0f\
invalid-payload\x01s\0\x0equota-exceeded\0\0\x06broker\x01s\0\x0fbroker-rejected\
\x01s\0\x04\0\x12mqtt-publish-error\x03\0\0\x01p}\x01ks\x01j\0\x01\x01\x01@\x06\x06\
clients\x05topics\x07payload\x02\x0ccontent-type\x03\x03qos}\x06retain\x7f\0\x04\
\x04\0\x0cmqtt-publish\x01\x05\x03\0\x1abrenn:processor/mqtt@0.1.0\x05\x05\x01B\x08\
\x01q\x06\x0bnot-granted\0\0\x06denied\x01s\0\x0cinvalid-args\x01s\0\x0crate-lim\
ited\0\0\x0bwrong-class\0\0\x08internal\x01s\0\x04\0\x0atool-error\x03\0\0\x01j\x01\
s\x01\x01\x01@\x02\x04tools\x09args-jsons\0\x02\x04\0\x09call-fast\x01\x03\x01j\0\
\x01\x01\x01@\x03\x04tools\x09args-jsons\x07call-ids\0\x04\x04\0\x0acall-async\x01\
\x05\x03\0\x1bbrenn:processor/tools@0.1.0\x05\x06\x01B\x0a\x01s\x04\0\x0denvelop\
e-json\x03\0\0\x01p\x01\x01r\x04\x04ports\x09envelopes\x02\x08new-fromy\x07dropp\
edy\x04\0\x0bport-window\x03\0\x03\x01p\x04\x01r\x01\x05ports\x05\x04\0\x0aactiv\
ation\x03\0\x06\x01q\x02\x12malformed-envelope\x01s\0\x11processing-failed\x01s\0\
\x04\0\x0dreceive-error\x03\0\x08\x03\0\x1bbrenn:processor/types@0.1.0\x05\x07\x02\
\x03\0\x07\x0aactivation\x03\0\x0aactivation\x03\0\x08\x02\x03\0\x07\x0dreceive-\
error\x03\0\x0dreceive-error\x03\0\x0a\x01j\0\x01\x0b\x01@\x01\x01a\x09\0\x0c\x04\
\0\x07receive\x01\x0d\x04\0\x1fbrenn:processor/processor@0.1.0\x04\0\x0b\x0f\x01\
\0\x09processor\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\
\x070.251.0\x10wit-bindgen-rust\x060.58.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen_rt::maybe_link_cabi_realloc();
}

