// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type CheckInput = brenn::replay::types::CheckInput;
pub type ReplayError = brenn::replay::types::ReplayError;
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_check_cabi<T_: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i64,arg5: *mut u8,arg6: usize,arg7: *mut u8,arg8: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result10 = {
  let base6 = arg0;
  let len6 = arg1;
  let mut result6 = _rt::Vec::with_capacity(len6);
  for i in 0..len6 {
    let base = base6.add(i * (4*::core::mem::size_of::<*const u8>()));
    let e6 = {
      let l0 = *base.add(0).cast::<*mut u8>();
      let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      let len2 = l1;
      let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
      let l3 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l4 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let len5 = l4;
      let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

      brenn::replay::types::Header{
        name: _rt::string_lift(bytes2),
        value: _rt::string_lift(bytes5),
      }
    };
    result6.push(e6);
  }
  _rt::cabi_dealloc(base6, len6 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
  let len7 = arg3;
  let len8 = arg6;
  let bytes8 = _rt::Vec::from_raw_parts(arg5.cast(), len8, len8);
  let len9 = arg8;
  let bytes9 = _rt::Vec::from_raw_parts(arg7.cast(), len9, len9);
  T_::check(brenn::replay::types::CheckInput{
    headers: result6,
    body: <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(arg2.cast(), len7, len7)),
    received_at: arg4 as u64,
    key_id: _rt::string_lift(bytes8),
    endpoint_slug: _rt::string_lift(bytes9),
  })
};
let ptr11 = (&raw mut _RET_AREA.0).cast::<u8>();
match result10 {
  Ok(_) => { {
    *ptr11.add(0).cast::<u8>() = (0i32) as u8;
  } },
  Err(e) => { {
    *ptr11.add(0).cast::<u8>() = (1i32) as u8;
    use brenn::replay::types::ReplayError as V13;
    match e {
      V13::TimestampOutOfWindow=> {
        {
          *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
        }
      }
      V13::Duplicate=> {
        {
          *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
        }
      }
      V13::MonotonicityViolation=> {
        {
          *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32) as u8;
        }
      }
      V13::TooManyRequests=> {
        {
          *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32) as u8;
        }
      }
      V13::MalformedInput(e) => {
        *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (4i32) as u8;
        let vec12 = (e.into_bytes()).into_boxed_slice();
        let ptr12 = vec12.as_ptr().cast::<u8>();
        let len12 = vec12.len();
        ::core::mem::forget(vec12);
        *ptr11.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
        *ptr11.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr12.cast_mut();
      },
    }
  } },
};ptr11
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_check<T_: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => (),
    _ => {
      let l1 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
      match l1 {
        0 => (),
        1 => (),
        2 => (),
        3 => (),
        _ => {
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l3 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l2, l3, 1);
        },
      }
    },
  }
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn check(input: CheckInput,) -> Result<(),ReplayError>;
}
#[doc(hidden)]

macro_rules! __export_world_replay_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "check")]
    unsafe extern "C" fn export_check(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i64,arg5: *mut u8,arg6: usize,arg7: *mut u8,arg8: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_check_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) }
    }
    #[unsafe(export_name = "cabi_post_check")]
    unsafe extern "C" fn _post_return_check(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_check::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_replay_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
#[allow(dead_code, clippy::all)]
pub mod brenn {
  pub mod replay {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod store {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// Opaque handle to an in-flight transaction. The host owns the resource;
      /// the component receives an index and must commit or rollback before the
      /// instance returns from its export call. A handle dropped without
      /// commit/rollback is a contract violation — the host's HostTransaction::drop
      /// detects the still-active tx via the tx_active flag, attempts a cleanup
      /// rollback, then returns Err(...) (wasmtime treats a destructor-returned Err
      /// as a runtime trap). The trap surfaces to the host as Err(wasmtime::Error)
      /// on the owning check call, which ReplayComponent::check then collapses to
      /// a panic per CLAUDE.md fail-fast rules.

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Transaction{
        handle: _rt::Resource<Transaction>,
      }

      impl Transaction{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Transaction{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]transaction"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      /// All store failures the component can observe.
      #[derive(Clone)]
      pub enum StoreError {
        /// Another writer holds the lock and the host's wait budget was
        /// exhausted. Transient. Reserved; not produced in iter-2 (the
        /// process-global path guard precludes cross-instance contention).
        Contention,
        /// Storage subsystem failure or contract violation. String is
        /// host-side diagnostic, opaque to the component. Covers nested
        /// begin, SQLite errors, file corruption.
        Backend(_rt::String),
        /// Host-enforced per-store size cap reached. The write was rejected
        /// atomically; no partial state committed. Distinct from backend(...)
        /// (disk-full / corruption): this is the host's own quota, recoverable
        /// by the guest's prune/delete path.
        QuotaExceeded,
      }
      impl ::core::fmt::Debug for StoreError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            StoreError::Contention => {
              f.debug_tuple("StoreError::Contention").finish()
            }
            StoreError::Backend(e) => {
              f.debug_tuple("StoreError::Backend").field(e).finish()
            }
            StoreError::QuotaExceeded => {
              f.debug_tuple("StoreError::QuotaExceeded").finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for StoreError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for StoreError {}
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Read a value for (namespace, key) within this transaction. Returns
        /// none if the key is absent. Errors are storage-layer failures.
        #[allow(async_fn_in_trait)]
        pub fn get(&self,namespace: &str,key: &[u8],) -> Result<Option<_rt::Vec::<u8>>,StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = key;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.get"]
              fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import3((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
            let l4 = i32::from(*ptr2.add(0).cast::<u8>());
            let result14 = match l4 {
              0 => {
                let e = {
                  let l5 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                  match l5 {
                    0 => None,
                    1 => {
                      let e = {
                        let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l7 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len8 = l7;

                        <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l6.cast(), len8, len8))
                      };
                      Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                  }
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l9 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v13 = match l9 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e13 = {
                        let l10 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l11 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len12 = l11;
                        let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                        _rt::string_lift(bytes12)
                      };
                      StoreError::Backend(e13)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v13
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result14
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Write or replace a value. Idempotent w.r.t. value equality.
        #[allow(async_fn_in_trait)]
        pub fn put(&self,namespace: &str,key: &[u8],value: &[u8],) -> Result<(),StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = key;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let vec2 = value;
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.put"]
              fn wit_import4(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import4(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import4((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2.cast_mut(), len2, ptr3);
            let l5 = i32::from(*ptr3.add(0).cast::<u8>());
            let result11 = match l5 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l6 = i32::from(*ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v10 = match l6 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e10 = {
                        let l7 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l8 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len9 = l8;
                        let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                        _rt::string_lift(bytes9)
                      };
                      StoreError::Backend(e10)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v10
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result11
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Delete a key. Absent key is a no-op (not an error).
        #[allow(async_fn_in_trait)]
        pub fn delete(&self,namespace: &str,key: &[u8],) -> Result<(),StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = key;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.delete"]
              fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import3(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import3((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
            let l4 = i32::from(*ptr2.add(0).cast::<u8>());
            let result10 = match l4 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l5 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v9 = match l5 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e9 = {
                        let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l7 = *ptr2.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len8 = l7;
                        let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                        _rt::string_lift(bytes8)
                      };
                      StoreError::Backend(e9)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v9
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result10
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// List keys in namespace in ascending key order, between start (inclusive)
        /// and end (exclusive). end = none means to-the-end. limit = 0 means
        /// unlimited. Returns (key, value) pairs.
        #[allow(async_fn_in_trait)]
        pub fn scan(&self,namespace: &str,start: &[u8],end: Option<&[u8]>,limit: u32,) -> Result<_rt::Vec::<(_rt::Vec::<u8>,_rt::Vec::<u8>,)>,StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = namespace;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec1 = start;
            let ptr1 = vec1.as_ptr().cast::<u8>();
            let len1 = vec1.len();
            let (result3_0,result3_1,result3_2,) = match end {
              Some(e) => {
                let vec2 = e;
                let ptr2 = vec2.as_ptr().cast::<u8>();
                let len2 = vec2.len();

                (1i32, ptr2.cast_mut(), len2)
              },
              None => {
                (0i32, ::core::ptr::null_mut(), 0usize)
              },
            };let ptr4 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.scan"]
              fn wit_import5(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import5(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, ) { unreachable!() }
            wit_import5((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, result3_0, result3_1, result3_2, _rt::as_i32(&limit), ptr4);
            let l6 = i32::from(*ptr4.add(0).cast::<u8>());
            let result21 = match l6 {
              0 => {
                let e = {
                  let l7 = *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l8 = *ptr4.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base15 = l7;
                  let len15 = l8;
                  let mut result15 = _rt::Vec::with_capacity(len15);
                  for i in 0..len15 {
                    let base = base15.add(i * (4*::core::mem::size_of::<*const u8>()));
                    let e15 = {
                      let l9 = *base.add(0).cast::<*mut u8>();
                      let l10 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len11 = l10;
                      let l12 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l13 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len14 = l13;

                      (<_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l9.cast(), len11, len11)), <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l12.cast(), len14, len14)))
                    };
                    result15.push(e15);
                  }
                  _rt::cabi_dealloc(base15, len15 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());

                  result15
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l16 = i32::from(*ptr4.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v20 = match l16 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e20 = {
                        let l17 = *ptr4.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l18 = *ptr4.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len19 = l18;
                        let bytes19 = _rt::Vec::from_raw_parts(l17.cast(), len19, len19);

                        _rt::string_lift(bytes19)
                      };
                      StoreError::Backend(e20)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v20
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result21
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Commit the transaction. The handle is consumed (resource dropped).
        /// On COMMIT failure, host attempts ROLLBACK; if that also fails, the
        /// host panics (fail-fast). The component sees only store-error on the
        /// structured failure path.
        #[allow(async_fn_in_trait)]
        pub fn commit(&self,) -> Result<(),StoreError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.commit"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result8 = match l2 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v7 = match l3 {
                    0 => {
                      StoreError::Contention
                    }
                    1 => {
                      let e7 = {
                        let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l5 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                        _rt::string_lift(bytes6)
                      };
                      StoreError::Backend(e7)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      StoreError::QuotaExceeded
                    }
                  };

                  v7
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result8
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Abort the transaction. The handle is consumed.
        #[allow(async_fn_in_trait)]
        pub fn rollback(&self,) -> (){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.rollback"]
              fn wit_import0(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) { unreachable!() }
            wit_import0((self).handle() as i32);
          }
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// Start a new transaction. SQLite BEGIN IMMEDIATE under the hood:
      /// acquires the write lock now. A second begin from the same component
      /// instance before commit/rollback returns backend("nested transaction
      /// not supported"). The contention variant is reserved for iter-3+.
      #[allow(async_fn_in_trait)]
      pub fn begin() -> Result<Transaction,StoreError>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:replay/store@0.1.0")]
          unsafe extern "C" {
            #[link_name = "begin"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result9 = match l2 {
            0 => {
              let e = {
                let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<i32>();

                Transaction::from_handle(l3 as u32)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l4 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                let v8 = match l4 {
                  0 => {
                    StoreError::Contention
                  }
                  1 => {
                    let e8 = {
                      let l5 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                      let l6 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len7 = l6;
                      let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                      _rt::string_lift(bytes7)
                    };
                    StoreError::Backend(e8)
                  }
                  n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    StoreError::QuotaExceeded
                  }
                };

                v8
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result9
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod config {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      /// Read one operator-supplied config value. Values are opaque strings;
      /// the guest parses. The map is fixed for the process lifetime (seeded
      /// from host TOML at startup; changes require a host restart). Keys
      /// under the reserved prefix "brenn." are host-injected facts (e.g.
      /// "brenn.max-skew-secs" on replay components bound to a timestamped
      /// signature scheme); operator TOML cannot set them.
      #[allow(async_fn_in_trait)]
      pub fn get(key: &str,) -> Option<_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = key;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "brenn:replay/config@0.1.0")]
          unsafe extern "C" {
            #[link_name = "get"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result7 = match l3 {
            0 => None,
            1 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;
                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                _rt::string_lift(bytes6)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result7
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// Wall-clock instant. Milliseconds since Unix epoch, UTC.
      /// Host produces; component treats as opaque ordering key.
      pub type InstantMillis = u64;
      /// One HTTP header. Name is lowercased canonical form. Value is the
      /// header's UTF-8 representation. (HTTP allows non-UTF-8 header bytes
      /// in principle; no surveyed webhook provider uses any. The host
      /// rejects non-UTF-8 header values before reaching the component, so
      /// the component never sees invalid UTF-8 here.)
      #[derive(Clone)]
      pub struct Header {
        pub name: _rt::String,
        pub value: _rt::String,
      }
      impl ::core::fmt::Debug for Header {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Header").field("name", &self.name).field("value", &self.value).finish()
        }
      }
      /// Inputs sufficient for any surveyed webhook replay scheme.
      /// The component owns per-provider extraction (which header(s) it
      /// reads, whether it parses the body) — that policy lives with the
      /// per-endpoint replay component, not the host.
      #[derive(Clone)]
      pub struct CheckInput {
        /// All request headers as received, lowercased names. The host
        /// passes everything; per-provider filtering happens inside the
        /// component. (A future optional `config` export can let the
        /// component declare an allowlist so the host pre-filters; this
        /// is purely additive and not part of iter 1. See design §2.2.1.)
        pub headers: _rt::Vec::<Header>,
        /// Verified raw request body bytes (same bytes that were
        /// HMAC-verified by the host). The component parses provider
        /// envelopes itself if it needs to.
        pub body: _rt::Vec::<u8>,
        /// Host wall-clock at request receipt, for skew-window checks.
        pub received_at: InstantMillis,
        /// Identity surfaced by the host signature layer (matched HMAC
        /// key id or bearer token id). Mirrors
        /// brenn-lib::webhook::signature::VerifiedRequest.key_id.
        /// Empty string is permitted for schemes with no key id.
        pub key_id: _rt::String,
        /// Endpoint slug from ResolvedWebhookEndpoint.slug. Lets a
        /// component namespace its state across endpoints if it serves
        /// more than one.
        pub endpoint_slug: _rt::String,
      }
      impl ::core::fmt::Debug for CheckInput {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("CheckInput").field("headers", &self.headers).field("body", &self.body).field("received-at", &self.received_at).field("key-id", &self.key_id).field("endpoint-slug", &self.endpoint_slug).finish()
        }
      }
      /// Generic verdict variants. Names are provider-agnostic; specific
      /// providers' notions of "stale" / "duplicate" map onto these.
      #[derive(Clone)]
      pub enum ReplayError {
        /// received-at vs. provider-asserted send-time exceeds the
        /// component's skew window (phonebuddy: 24h; Stripe/Slack: 5m).
        TimestampOutOfWindow,
        /// The component recognizes this request as a duplicate of one
        /// it has already accepted (e.g. nonce reuse, delivery-id seen).
        Duplicate,
        /// Per-key monotonicity violation (e.g. phonebuddy's per-client
        /// sent_at strict-increase rule). Distinct from duplicate:
        /// this is an older-than-last-seen, not a same-as-already-seen.
        MonotonicityViolation,
        /// The component has observed enough recent activity from this
        /// caller that it considers further requests abuse rather than
        /// ordinary traffic, and is failing closed. Distinct from
        /// `duplicate` and `monotonicity-violation`: those reject a single
        /// request as out-of-protocol; this rejects the caller as a whole
        /// pending decay of the activity window. The host routes this to a
        /// dedicated fail2ban lane.
        TooManyRequests,
        /// Component could not extract its required fields from the
        /// provided input (e.g. malformed envelope, missing expected
        /// header). String carries a component-side diagnostic.
        /// Distinct from a host-side parse failure: the host already
        /// verified the body's HMAC, so this implies a producer bug,
        /// not adversarial input.
        MalformedInput(_rt::String),
      }
      impl ::core::fmt::Debug for ReplayError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            ReplayError::TimestampOutOfWindow => {
              f.debug_tuple("ReplayError::TimestampOutOfWindow").finish()
            }
            ReplayError::Duplicate => {
              f.debug_tuple("ReplayError::Duplicate").finish()
            }
            ReplayError::MonotonicityViolation => {
              f.debug_tuple("ReplayError::MonotonicityViolation").finish()
            }
            ReplayError::TooManyRequests => {
              f.debug_tuple("ReplayError::TooManyRequests").finish()
            }
            ReplayError::MalformedInput(e) => {
              f.debug_tuple("ReplayError::MalformedInput").field(e).finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for ReplayError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for ReplayError {}

    }

  }
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen_rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_replay_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_replay_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_replay_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.58.0:brenn:replay@0.1.0:replay:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1090] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc5\x07\x01A\x02\x01\
A\x0d\x01B\x1b\x04\0\x0btransaction\x03\x01\x01q\x03\x0acontention\0\0\x07backen\
d\x01s\0\x0equota-exceeded\0\0\x04\0\x0bstore-error\x03\0\x01\x01h\0\x01p}\x01k\x04\
\x01j\x01\x05\x01\x02\x01@\x03\x04self\x03\x09namespaces\x03key\x04\0\x06\x04\0\x17\
[method]transaction.get\x01\x07\x01j\0\x01\x02\x01@\x04\x04self\x03\x09namespace\
s\x03key\x04\x05value\x04\0\x08\x04\0\x17[method]transaction.put\x01\x09\x01@\x03\
\x04self\x03\x09namespaces\x03key\x04\0\x08\x04\0\x1a[method]transaction.delete\x01\
\x0a\x01o\x02\x04\x04\x01p\x0b\x01j\x01\x0c\x01\x02\x01@\x05\x04self\x03\x09name\
spaces\x05start\x04\x03end\x05\x05limity\0\x0d\x04\0\x18[method]transaction.scan\
\x01\x0e\x01@\x01\x04self\x03\0\x08\x04\0\x1a[method]transaction.commit\x01\x0f\x01\
@\x01\x04self\x03\x01\0\x04\0\x1c[method]transaction.rollback\x01\x10\x01i\0\x01\
j\x01\x11\x01\x02\x01@\0\0\x12\x04\0\x05begin\x01\x13\x03\0\x18brenn:replay/stor\
e@0.1.0\x05\0\x01B\x03\x01ks\x01@\x01\x03keys\0\0\x04\0\x03get\x01\x01\x03\0\x19\
brenn:replay/config@0.1.0\x05\x01\x01B\x0a\x01w\x04\0\x0einstant-millis\x03\0\0\x01\
r\x02\x04names\x05values\x04\0\x06header\x03\0\x02\x01p\x03\x01p}\x01r\x05\x07he\
aders\x04\x04body\x05\x0breceived-at\x01\x06key-ids\x0dendpoint-slugs\x04\0\x0bc\
heck-input\x03\0\x06\x01q\x05\x17timestamp-out-of-window\0\0\x09duplicate\0\0\x16\
monotonicity-violation\0\0\x11too-many-requests\0\0\x0fmalformed-input\x01s\0\x04\
\0\x0creplay-error\x03\0\x08\x03\0\x18brenn:replay/types@0.1.0\x05\x02\x02\x03\0\
\x02\x0bcheck-input\x03\0\x0bcheck-input\x03\0\x03\x02\x03\0\x02\x0creplay-error\
\x03\0\x0creplay-error\x03\0\x05\x01j\0\x01\x06\x01@\x01\x05input\x04\0\x07\x04\0\
\x05check\x01\x08\x04\0\x19brenn:replay/replay@0.1.0\x04\0\x0b\x0c\x01\0\x06repl\
ay\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.251.0\x10\
wit-bindgen-rust\x060.58.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen_rt::maybe_link_cabi_realloc();
}

